MARS-LIKELION/NangPaGo

.github/workflows/ci.yml

[NPG-25] git actions test
[NPG-25]: https://mars-likelion.atlassian.net/browse/NPG-25?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NPG-25] git actions test

---

NangPaGo-fe/package-lock.json
NangPaGo-fe/package.json
NangPaGo-fe/src/App.jsx
NangPaGo-fe/src/common/Modal.jsx
NangPaGo-fe/src/common/utils/validation.js
NangPaGo-fe/src/components/SocialLoginButton/utils.js
NangPaGo-fe/src/components/login/SocialLoginButton.jsx
NangPaGo-fe/src/components/util/auth.js
NangPaGo-fe/src/main.jsx
NangPaGo-fe/src/pages/index.jsx
NangPaGo-fe/src/pages/login/LoginPage.jsx
NangPaGo-fe/vite.config.js

> 코드 모듈화 및 패키지 구조 변경
> react-router-dom 적용 
- 설치 방법: `npm i react-router-dom`
> 현재 메인페이지가 없어서 일단 `src/pages/index.jsx`  메인페이지 엘리멘트를 
로그인페이지로 해놔서 메인 작업하면 엘리멘트만 수정하면 됩니다.
- 프록시 설정(vite.config.js)을 설정 안 해도 된다고 해서 주석 처리 해놨는데 찾아봐야할 것 같습니다.
- App.jsx 현재 사용하지 않는데 나중에 사용할 지 몰라 일단 놔두었습니다.
- handleLoginClick() : 로그인 api와 통신할 함수

[NPG-33] refactor: 로그인 UI 작업 모듈화 및 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/jpa/BaseEntity.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/JpaAuditingConfig.java

- JPA Entity 작성 시 사용할 공통 코드 `BaseEntity` 작성

NPG-41 JPA BaseEntity 작성

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Manual.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/ManualImage.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/ManualImageRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/ManualRepository.java

[NPG-37] Recipe entity 작성

---

.gitignore
NangPaGo-data/create_food_dict.py

> DB 테이블 수정 (칼럼 추가 및 칼럼명 수정)
`MySQL`서버에 **반영 완료**

[NPG-30] DB 테이블 수정

---

NangPaGo-be/src/main/resources/application.yml

- 오래된 DB Connection Pool이 계속 남아있지 않도록 하는 설정 추가
- 잘 되는지 모니터링 필요함

NPG-58 개발환경 DB Connection pool 설정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/RefreshTokenDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/RefreshToken.java

[NO-ISSUE] Refresh token db 컬럼 순서 변경

---

NangPaGo-be/build.gradle
NangPaGo-be/src/main/resources/application.yml

- ES Build 에러 해결을 위해 build.gradle, application.yml 을 수정했습니다.
- 만약 서버 실행 실패한다면, .env 확인해주세요

[NO-ISSUE] ES build 관련 에러 해결

---

.github/workflows/ci.yml
NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepositoryTest.java

- CI 빌드 시 통합 Test 실행 제외
- 실제 DB 연결해야해서 제외시켰음.
- 통합 테스트는 pre-push 에서 하는걸로 변경 예정

[NPG-60] CI 환경에서 통합 Test 제외

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomSuccessHandler.java

[NO-ISSUE] fix(auth): 디비 저장할 때 토큰과 이메일 반대로 들어가는 버그 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/TokenController.java
NangPaGo-fe/src/api/axiosInstance.js

- Token 재발급 URI를 보다 직관적으로 변경하였습니다.
- `/auth/reissue` -> `/token/reissue`

[NPG-67] 토큰 재발급 URI 변경

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeRequestDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/ManualImageRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/ManualRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeService.java

[NPG-61] 레시피 상세페이지 API 구현

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/AuthController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/TokenService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
NangPaGo-fe/src/App.jsx

- 사용자 인증 코드 리팩터링
- TokenService 코드 리팩터링

[NPG-69] 사용자 인증, 토큰 재발급 코드 리팩터링

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-fe/src/components/common/Header.jsx
NangPaGo-fe/src/components/recipe/CookingSteps.jsx
NangPaGo-fe/src/components/recipe/IngredientList.jsx
NangPaGo-fe/src/components/recipe/NutritionInfo.jsx
NangPaGo-fe/src/components/recipe/Recipe.jsx
NangPaGo-fe/src/pages/recipe/RecipeDetail.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx
NangPaGo-fe/src/routes/Router.jsx

[NPG-61] 레시피 상세페이지 UI 구현

---

NangPaGo-fe/src/App.jsx
NangPaGo-fe/src/api/axiosInstance.js
NangPaGo-fe/src/components/common/Footer.jsx
NangPaGo-fe/src/components/recipe/CookingSteps.jsx
NangPaGo-fe/src/components/recipe/IngredientList.jsx
NangPaGo-fe/src/components/recipe/Recipe.jsx
NangPaGo-fe/src/pages/recipe/RecipeDetail.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx
NangPaGo-fe/src/slices/loginSlice.js

[NPG-61] 레시피 상세페이지 댓글 및 푸터 구현

---

NangPaGo-be/build.gradle
NangPaGo-be/gradle.properties
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SwaggerConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-be/src/main/resources/application.yml

[NPG-70] Swagger UI 사용 환경 구축

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentRequestDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/entity/RecipeComment.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java

[NPG-61] 레시피 댓글 api CRUD 구현

---

NangPaGo-fe/src/api/commentService.js
NangPaGo-fe/src/common/modal/DeleteModal.jsx
NangPaGo-fe/src/common/modal/LoginModal.jsx
NangPaGo-fe/src/components/recipe/Recipe.jsx
NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx

[NPG-61] 댓글 CRUD FE-BE 연동 테스트 완료

---

NangPaGo-fe/src/api/commentService.js
NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx

[NPG-61] 클라이언트에서 정상적으로 보내지만 서버에서 이메일이 null로 받는 버그 수정

---

NangPaGo-fe/src/api/commentService.js
NangPaGo-fe/src/components/common/Footer.jsx
NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx
NangPaGo-fe/src/pages/recipe/RecipeDetail.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx
NangPaGo-fe/src/routes/Router.jsx

[NPG-61] 불필요한 콘솔 및 주석 제거

---

NangPaGo-fe/src/components/recipe/Recipe.jsx

[NPG-61] [FE] 레시피 상세페이지 좋아요 구현

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/entity/RecipeComment.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeEsResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeLikeRequestDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeLikeResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/RecipeES.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/RecipeLike.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java

레시피 상세페이지 좋아요 로직 수정 및 디비 테이블 수정

[NPG-61] [BE] 레시피 상세페이지 좋아요 로직 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/NangPaGoApplication.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/common/dto/PageDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
NangPaGo-fe/src/api/commentService.js
NangPaGo-fe/src/components/recipe/CookingSteps.jsx
NangPaGo-fe/src/components/recipe/Recipe.jsx
NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx

레시피 좋아요 테스트 완료
댓글 페이징네이션 기능 추가

[NPG-73] 레시피 좋아요 서버 엔드포인트에 맞춰 프론트 수정 및 댓글 페이징네이션 기능 추가

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteRequestDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/entity/RecipeFavorite.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
NangPaGo-fe/src/components/recipe/Recipe.jsx

[NPG-73] 레시피 즐겨찾기 기능 추가

---

NangPaGo-be/src/main/resources/application.yml
NangPaGo-fe/Dockerfile
NangPaGo-fe/index.html
NangPaGo-fe/vite.config.js
docker-compose.yml

- 보안 강화를 위해 API Server Port를 기본 포트대신 다른 포트로 사용할 수 있도록 환경변수로부터 주입받을 수 있게 변경

[NPG-59] API Server Port 설정을 환경변수로 주입받도록 변경

---

.github/workflows/ci.yml

[NPG-59] CI/CD on Github yml 작성

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-fe/src/components/recipe/Recipe.jsx

[NPG-75] 레시피 entity, dto 수정 

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-fe/src/components/recipe/Recipe.jsx

[NO-ISSUE] NangPago release/1.0.0 merge to main

---

NangPaGo-fe/src/pages/login/Login.jsx

- 소셜 Login redirection URL을 환경변수로 주입받도록 변경하여, 개발 환경과 배포 환경에서 사용할 URL 분리

[NPG-77] 소셜 Login redirection URL 버그 수정

---

NangPaGo-be/gradle.properties
NangPaGo-fe/src/pages/login/Login.jsx

[NO-ISSUE] [NO-ISSUE] NangPago release/1.0.1 merge to main

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-fe/src/pages/login/Login.jsx

- OAuth2 로그인 URL 및 redirection URI 변경
- **환경변수 변경 필요**

[NO-ISSUE] 개발 환경과 배포 환경 OAuth2 관련 URL 통일

---

NangPaGo-be/gradle.properties
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-fe/src/pages/login/Login.jsx

[NO-ISSUE] NangPago release/1.0.2 merge to main

---

.github/workflows/cicd.yml
NangPaGo-be/gradle.properties
NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/GlobalExceptionHandler.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomLogoutFilter.java
NangPaGo-fe/src/components/common/Header.jsx

- v1.0.3 release
- logout URL 접두어로 인해 발생하는 버그 해결

[NO-ISSUE] NangPago release/1.0.3 merge to main

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx

DB에는 댓글을 작성할 때마다 1개씩 저장되지만 사용자가 작성 당시에는 2개 작성 되는 버그 수정
securitycofig: WITH_LIST 불필요한 URL 삭제

[NPG-75] 클라이언트에서 댓글 작성시 중복 작성한 것처럼 보이는 버그 수정

---

NangPaGo-fe/src/components/common/Header.jsx
NangPaGo-fe/src/slices/loginSlice.js

액세스 토큰이 재발급이 정상적으로 되어도 다른 페이지 이동시 풀림 현상 수정

[NPG-75] 액세스 토큰이 만료시 새로고침하면 로그인 풀림 버그 수정

---

NangPaGo-fe/src/components/recipe/Recipe.jsx

[NPG-75] 레시피 상세 페이지 해시태그 UI 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/util/JwtFilter.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java
NangPaGo-fe/src/components/recipe/Recipe.jsx

토큰 발급을 할 때 securityContext 에 저장한 사용자 이메일을 꺼내와서 인증

[NPG-75]  레시피 좋아요 사용자 인증 로직 변경

---

NangPaGo-be/src/main/resources/application.yml

[NPG-75] 네이버, 카카오 스코프 변경으로 인해 yml 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteRequestDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeLikeRequestDto.java
NangPaGo-fe/src/components/recipe/Recipe.jsx

[NPG-75] 즐겨찾기 사용자 인증 방식 변경

---

.githooks/pre-push

- 각자 로컬 환경에서 push 직전에 테스트를 수행하도록 `pre-push` 스크립트를 작성

[NPG-83] push 직전 테스트 수행을 위한 pre-push 스크립트 작성

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentRequestDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
NangPaGo-fe/src/components/recipe/comment/RecipeComment.jsx

댓글 응답 dto 이메일 마스킹 처리 후 전송으로 변경으로 자신이 작성한 글인지 확인하는 플래그 추가

[NPG-75] 댓글 응답 DTO 이메일 마스킹 처리 후 전송방식으로 변경

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteListResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsSynchronizerService.java
NangPaGo-fe/.gitignore

[NPG-87] 레시피 즐겨찾기 리스트 조회 API개발

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/controller/TokenController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/refrigerator/controller/RefrigeratorController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/AuthController.java

[NPG-63] Swagger 태그 추가

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java

keyword없이 검색 시 -> 랜덤으로 10개씩 데이터를 보여주어야 하는데 "검색 실패" 에러가 반환되는 버그 수정

[NPG-94] 키워드 없이 검색 시, 검색 실패 버그 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsSynchronizerService.java

[NPG-95] 칼로리 단위표시 

---

NangPaGo-be/src/main/resources/application.yml

- 개발 환경에서는 기존대로 로그를 콘솔에만 띄우고, 파일로 저장하지 않도록 profile을 local 과 prod 로 분리.
- 배포 환경에서 서버 로그를 파일로 저장시키도록 옵션 추가.

[NPG-81] 배포 환경에서 서버 로그를 파일로 남기도록 개선

---

NangPaGo-fe/src/components/recipe/Recipe.jsx
NangPaGo-fe/src/components/recipe/RecipeCard.jsx
NangPaGo-fe/src/components/recipe/RecipeListContent.jsx

- 레시피 리스트 조회 API 연동
- 리스트 UI 개선
- displayTag 를 Tag 스타일로 보여주도록 개선

[NPG-93] 레시피 리스트 UI 서버 연동 및 UI 개선

---

NangPaGo-fe/src/api/axiosInstance.js
NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
NangPaGo-fe/src/slices/loginSlice.js

추 후 서버에서 401 상태코드 전달하는 방식으로 변경 예정

[NPG-75] 로그인 상태유지 버그 수정

---

NangPaGo-fe/src/main.jsx

- StrictMode 로 인해 React 화면이 매번 두번 렌더링 되는 현상
- 공식문서상으로는 배포 모드에서는 자동으로 OFF된다고 하는데, 우리 환경에서는 그렇지 않아서 원인을 찾아야 하는 상황.
- 원인 찾기 전까지는 OFF 상태로 유지할 예정.

[NO-ISSUE] React StrictMode 제거

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/dto/IngredientEsResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/Ingredient.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/IngredientEs.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientEsService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientEsSynchronizer.java
NangPaGo-be/src/main/resources/elastic/ingredient/post-mapping.json
NangPaGo-be/src/main/resources/elastic/ingredient/post-setting.json
NangPaGo-data/README.md
NangPaGo-data/elastic/ingredients_dictionary/create_bulk_type.py
NangPaGo-data/elastic/ingredients_dictionary/init_index_ingredients_dictionary.sh
NangPaGo-data/mysql/ingredients_dictionary/init_csv2sql_ingredients_dictionary.py
NangPaGo-data/mysql/ingredients_dictionary/query/create_ingredients_dictionary.sql
NangPaGo-data/mysql/ingredients_dictionary/query/insert_ingredients_dictionary.sql

- Ingredient_id 칼럼 추가로 인한 리팩토링
- `NangPaGo-data/`: MySQL 스키마, Bulk Type 변경
- `NangPaGo-be/`: BackEnd 코드 수정 (Entity, Service)

[NPG-89] Ingredient_id 칼럼 추가로 인한 리팩토링

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/dto/RecipeFavoriteListResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java

[NPG-80]레시피 즐겨찾기 기능 관련 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/Ingredient.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-be/src/main/resources/application.yml
NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepositoryTest.java
NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeServiceTest.java
NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/refrigerator/repository/RefrigeratorRepositoryTest.java
NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/refrigerator/service/RefrigeratorServiceTest.java
NangPaGo-be/src/test/java/com/mars/NangPaGo/support/AbstractRepositoryTestSupport.java
NangPaGo-be/src/test/java/com/mars/NangPaGo/support/IntegrationTestSupport.java

- Service 레이어 통합테스트 시 `_TEST` 데이터베이스를 바라보도록 개선
- `@SpringBootTest` 추상화 Support 클래스 추가

[NPG-53] 통합테스트 Support Utility 추가

---

NangPaGo-fe/src/api/recipe.js
NangPaGo-fe/src/api/refrigerator.js
NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
NangPaGo-fe/src/routes/Router.jsx
NangPaGo-fe/src/slices/loginSlice.js

refactor: 냉장고 식재료로 추천 레시피 구현

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-fe/src/api/recipe.js
NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
NangPaGo-fe/src/routes/Router.jsx

추천 레시피 UI 사용자가 끝까지 스크롤 시 다음 추천 레시피가 있으면 보여주도록 변경

[NPG-76] 추천 레시피 UI 변경

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserInfoRequestDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserInfoResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/entity/User.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/repository/UserRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java

- 회원 정보 수정 관련 기능 추가
- 회원 정보 수정 전 조회
- 닉네임 중복 확인
-  회원 정보 수정

[NPG-74] 회원 정보 수정 기능 구현

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeService.java

[NPG-76] 레시피 like 메서드 명 변경

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserInfoResponseDto.java

- 회원정보 수정 페이지에서 연동계정 정보를 사용안하기로 하면서 Dto만 수정했습니다.

[NPG-101] 사용 안하는 Dto 컬럼 삭제

---

NangPaGo-fe/src/components/common/CreateButton.jsx
NangPaGo-fe/src/components/common/TopButton.jsx
NangPaGo-fe/src/components/recipe/Recipe.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx
NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx

메인페이지, 레시피 상세페이지, 레시피 추천 페이지 탑버튼  구현
게시글 작성 버튼 구현

[NOISSUE] 탑버튼 구현

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityLikeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityLikeResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/CommunityLike.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityLikeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityLikeService.java

[NPG-109] 커뮤니티 게시물 좋아요 기능 API 구현

---

NangPaGo-be/.gitignore
NangPaGo-be/build.gradle
NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/config/firebase/FirebaseConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/firebase/controller/FirebaseStorageController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/firebase/service/FirebaseStorageService.java
NangPaGo-be/src/main/resources/application.yml
NangPaGo-be/src/test/java/com/mars/NangPaGo/support/AbstractRepositoryTestSupport.java
NangPaGo-be/src/test/java/com/mars/NangPaGo/support/IntegrationTestSupport.java

[NPG-99] 이미지 업로드를 위한 firebase 연동

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/controller/CommunityCommentController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/service/CommunityCommentService.java

[NPG-107] 커뮤니티 댓글 관련 주석 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/builder/EsRecipeSearchQueryBuilder.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
NangPaGo-fe/src/components/recipe/Recipe.jsx
NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
NangPaGo-fe/src/components/search/SearchBar.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx
NangPaGo-fe/src/pages/search/RecipeSearch.jsx
NangPaGo-fe/src/routes/Router.jsx

- '추천 페이지' 화면에서 레시피명으로 검색할 수 있도록 기능을 구현하였습니다.

[NPG-104] 레시피명으로 레시피 검색 기능 구현

---

.github/workflows/cicd.yml

- Firebase secret key를 CI/CD 파이프라인 구동 시 프로젝트에 포함되도록 스크립트를 변경하였습니다.

[NPG-110] CI/CD 파이프라인에 Firebase secret key 포함되도록 변경

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteService.java
NangPaGo-fe/src/api/axiosInstance.js
NangPaGo-fe/src/api/recipe.js
NangPaGo-fe/src/components/common/Footer.jsx
NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
NangPaGo-fe/src/components/search/SearchBar.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx
NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
NangPaGo-fe/src/pages/search/RecipeSearch.jsx
NangPaGo-fe/src/pages/search/RefrigeratorSearch.jsx

즐겨찾기 같은 경우는 현재 다음 페이지의 데이터 보여줄 때 자연스럽지 않음. --추 후 수정--

[NPG-97] 추천레시피, 즐겨찾기 무한 스크롤 구현

---

NangPaGo-fe/src/components/recipe/Recipe.jsx

레시피 좋아요 상태 api 데이터 응답이 바껴 클아이언트 코드 수정

[NPG-113] 레시피 좋아요 상태 API 데이터 응답 변경 대응

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/builder/EsRecipeSearchQueryBuilder.java

- randomScore 사용 시, field 값을 명시해주지 않으면 경고가 표시되는 문제를 해결.
- ElasticSearch 7.0 이상부터 변경된 사항

[NO-ISSUE] ES warning 해결

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/config/security/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/controller/CommunityCommentController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/service/CommunityCommentService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityLikeResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityRequestDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/Community.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java

- Community Entity와 Dto 수정
- 게시물 CRUD 구현 (제목, 내용, 공개여부)

[NPG-108] 게시물 CRUD 구현

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
NangPaGo-fe/src/components/common/Header.jsx
NangPaGo-fe/src/components/mypage/UserInfoModify.jsx
NangPaGo-fe/src/slices/loginSlice.js

- UI 헤더에 보여주고 있던 사용자명을 `nickname`으로 보여주도록 변경
- 닉네임 중복 및 유효성 검증 로직을 서버로 이관

[NPG-119] UI 헤더 - `nickname`으로 보여주도록 변경, 검증 로직 개선

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsSynchronizerService.java

- bulk-update 시, 기존 데이터 제거 후 삽입하도록 변경

[NO-ISSUE] ES recipes 인덱스 bulk-update 지우고 다시쓰기

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityLikeController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityLikeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityLikeService.java

[NPG-108] 게시물 좋아요 개수 조회 API 추가 

---

NangPaGo-fe/src/api/recipe.js
NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx

추천 레시피 마지막 데이터인데 스크롤을 할 때마다 api 무한 호출 수정

[NO_ISSUE] 무한 재요청 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java

[NO-ISSU] 게시글 단일 조회 권한 로직 개선

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeEsResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
NangPaGo-fe/src/pages/search/RecipeSearch.jsx

- 레시피 검색 화면의 자동완성 가독성 개선 및 식재료 검색 화면과 통일감을 위해 highlight 적용

[NPG-124] 레시피 검색 화면 자동완성 highlight 적용

---

NangPaGo-fe/src/components/search/SearchBar.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx
NangPaGo-fe/src/pages/search/RecipeSearch.jsx
NangPaGo-fe/src/pages/search/RefrigeratorSearch.jsx

- 레시피 검색어가 입력되어 있는 상태에서, 'X' 버튼을 클릭하면 검색어가 초기화되도록 해놓았음.
- 그런데, 'X'버튼이 아닌 다른 영역을 클릭해도 초기화가 되는 버그가 발생하였고, 이를 해결하였음.
- 추가 수정사항
- 메인 페이지 외의 검색 페이지(레시피, 식재료)에도 'X'버튼 적용함.

[NPG-144] 검색어 입력 영역 클릭시 초기화되는 버그 해결

---

NangPaGo-fe/src/api/community.js
NangPaGo-fe/src/api/communityComment.js
NangPaGo-fe/src/components/community/Community.jsx
NangPaGo-fe/src/components/community/comment/CommunityComment.jsx
NangPaGo-fe/src/pages/community/CommunityDetail.jsx
NangPaGo-fe/src/routes/Router.jsx

- 기본적인 틀 만들기 완료
```
제목
이미지
마스킹된이메일
좋아요토글
게시물내용
댓글
```
- 단일 조회 게시물에서의 `수정 버튼` 구현은 내일 회의 후 시작하면 될 것 같습니다.

[NPG-125] 커뮤니티 게시물 단일조회 FE 구현

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityRequestDto.java
NangPaGo-fe/src/api/community.js
NangPaGo-fe/src/components/common/ErrorMessage.jsx
NangPaGo-fe/src/components/common/SubmitButton.jsx
NangPaGo-fe/src/components/community/Community.jsx
NangPaGo-fe/src/components/community/FileUpload.jsx
NangPaGo-fe/src/components/community/TextArea.jsx
NangPaGo-fe/src/components/community/TextInput.jsx
NangPaGo-fe/src/pages/community/CommunityDetail.jsx
NangPaGo-fe/src/pages/community/CreateCommunity.jsx
NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
NangPaGo-fe/src/routes/Router.jsx

- 게시글 수정 구현
- 게시글 작성 및 수정 공통 부분 모듈화

[NO-ISSUE] 게시글 수정 구현 및 공통 컴포넌트 모듈화

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/repository/RecipeLikeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/MyPageDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
NangPaGo-fe/package-lock.json
NangPaGo-fe/package.json
NangPaGo-fe/src/api/myPage.js
NangPaGo-fe/src/components/common/Header.jsx
NangPaGo-fe/src/components/profile/ItemList.jsx
NangPaGo-fe/src/components/profile/ProfileHeader.jsx
NangPaGo-fe/src/components/profile/ProfileTabs.jsx
NangPaGo-fe/src/pages/mypage/Modify.jsx
NangPaGo-fe/src/pages/mypage/Profile.jsx
NangPaGo-fe/src/routes/Router.jsx

메뉴별 탭 메뉴 기능 추가
- 냉장고 탭 삭제 (추 후 레시피 게시글 탭 추가 예정)

[NPG-103] 마이페이지 메뉴별 조회 기능 추가

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/entity/Community.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java

- 게시글 소유자 확인 로직이 잘못되어 있는 부분을 고쳤습니다.
- 리팩토링을 진행했습니다.

[NO-ISSUE] 커뮤니티 - 게시글 소유자 확인 로직 버그 수정

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/repository/CommunityCommentRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityLikeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java
NangPaGo-fe/src/pages/community/CommunityList.jsx

- 좋아요 & 댓글 집계 API 구현
- 좋아요 & 댓글 집계 UI 구현

[NPG-128] 커뮤니티 전체 조회 - 좋아요 & 댓글 집계 API 구현

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/repository/CommunityCommentRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/dto/CommunityResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/repository/CommunityLikeRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/service/CommunityService.java
NangPaGo-fe/src/components/community/Community.jsx
NangPaGo-fe/src/pages/community/CommunityList.jsx

- 게시물 상세피이지 이메일의 경우, 마스킹된 이메일 + 길이 제한

[NPG-125] 커뮤니티 단일조회 게시물 - 마스킹된 이메일 길이 제한

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/NangPaGoApplication.java
NangPaGo-fe/src/components/common/CreateButton.jsx
NangPaGo-fe/src/components/community/Community.jsx
NangPaGo-fe/src/components/community/TextArea.jsx
NangPaGo-fe/src/pages/community/CommunityDetail.jsx
NangPaGo-fe/src/pages/community/CommunityList.jsx
NangPaGo-fe/src/pages/community/CreateCommunity.jsx
NangPaGo-fe/src/pages/community/ModifyCommunity.jsx

- 본인이 작성한 게시물에서 사이드 버튼을 누르면 토글
- 본인이 작성한 게시물이 아닌 경우에는 글쓰기 버튼

[NO-ISSUE] 게시물 CRUD 구현

---

NangPaGo-fe/src/pages/community/CreateCommunity.jsx
NangPaGo-fe/src/pages/mypage/Profile.jsx

[NO-ISSUE] 무한스크롤 렌더링 시 같은 ID 부여 필터 적용

---

NangPaGo-fe/src/api/myPage.js
NangPaGo-fe/src/pages/mypage/Profile.jsx

[NO-ISSUE] 탭이동시 디바운스 적용

---

NangPaGo-fe/src/components/common/Footer.jsx

[NO-ISSSUE] 서비스 피드백 링크 추가

---

NangPaGo-fe/src/pages/mypage/Modify.jsx

[NO-ISSUE] 마이페이지 레이아웃 문제 해결

---

NangPaGo-fe/src/components/common/Header.jsx
NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx

[NO-ISSUE] 메인페이지 즐겨찾기 탭 텍스트 변경

---

NangPaGo-be/gradle.properties
NangPaGo-fe/src/components/common/Footer.jsx
NangPaGo-fe/src/components/common/Header.jsx
NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
NangPaGo-fe/src/pages/mypage/Modify.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx

[NO-ISSUE] NangPago release/1.3.1 merge to main

---

NangPaGo-fe/src/pages/community/CreateCommunity.jsx

커뮤니티 - 게시물 작성 - 비공개 체크박스 설명 제거

[NPG-138] 커뮤니티 비공개 체크박스에 설명 제거

---

NangPaGo-fe/src/components/recipe/Recipe.jsx

[NPG-137] BugFix - UI에서 불필요한 소스 field 제거

---

NangPaGo-fe/src/api/community.js
NangPaGo-fe/src/components/community/Community.jsx

- 좋아요 상태 api 호출 수정 및 api 호출 코드 분리

[NPG-139] 좋아요 상태 버그 수정

---

NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
NangPaGo-fe/src/components/recipe/RecipeListTab.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx

로그인 전 : 즐겨찾기 탭 비활성화
로그인 후 : 즐겨찾기 탭 활성화

[NPG-146] 로그인 전/후 즐겨찾기 탭 수정

---

NangPaGo-fe/src/pages/community/CreateCommunity.jsx
NangPaGo-fe/src/pages/community/ModifyCommunity.jsx

[NPG-133] BugFix - UI에서 사진을 변경하지 않았을 때 기존 이미지가 유지되도록 수정

---

NangPaGo-fe/src/components/common/Header.jsx

- 현재 내가 보고 있는 페이지가 어디인지 더 명확하게 알 수 있게 활성화/비활성화 기능 추가
- 아이콘 아래에 페이지에 대한 제목 표시

[NPG-143] UI 헤더 현재 위치 표시(활성화) 및 제목 표시

---

NangPaGo-fe/src/components/common/Header.jsx

header - navigation 수정
- 상세페이지로 들어가면, 현재 위치가 다시 회색으로 바뀌는 부분 수정
- 회색 -> secondary(연두색)으로 색상 변경
- 유저아이콘: 드롭다운 리스트 위치 조정
- 아이콘만 링크 태그로 감싸져 있었음 -> 페이지제목도 링크 태그안에 넣어줌

[NPG-152] UI 헤더 - 현재 위치 구분, 아이콘 색상 변경, 드롭다운 위치 조정

---

NangPaGo-fe/src/common/modal/FileSizeErrorModal.jsx
NangPaGo-fe/src/pages/community/CreateCommunity.jsx
NangPaGo-fe/src/pages/community/ModifyCommunity.jsx

- 10MB 이상 이미지 업로드 시 모달 표시
- 10MB 예시 이미지는 `Jira 티켓`에 첨부되어 있습니다.

[NPG-141] 커뮤니티 게시물 - 이미지 업로드 용량 10MB 제한 추가

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/handler/OAuth2SuccessHandler.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/service/OAuth2UserService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/service/OAuth2ProviderTokenService.java
NangPaGo-fe/src/pages/error/OAuthError.jsx
NangPaGo-fe/src/routes/Router.jsx

- 같은 이메일인데 다른 Provider 로 가입을 시도하는 경우, 사용자에게 alert을 보여주도록 기능 추가

[NPG-136] 중복 회원가입 방지 로직

---

NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx

리스트 화면에서 상세페이지 진입 → 좋아요 클릭
다시 리스트로 돌아왔을 때, 좋아요 개수 변경 사항이 반영이 안되어있음.

[NPG-142] 레시피 좋아요 갯수 sync 안맞는 문제

---

NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx

내 냉장고에 식재료가 없을경우 '레시피 찾기'버튼 비활성화

[NPG-154] 식재료가 없을경우 '레시피 찾기'버튼 비활성화

---

NangPaGo-fe/package-lock.json
NangPaGo-fe/package.json
NangPaGo-fe/src/components/refrigerator/IngredientList.jsx
NangPaGo-fe/src/pages/refrigerator/Refrigerator.jsx
NangPaGo-fe/tailwind.config.js

체크 박스 추가
tailwind form 추가
전체선택기능 추가

[NPG-156] 냉장고 식재료 체크박스 추가 

---

Jenkinsfile
docker/docker-compose.blue.yml
docker/docker-compose.green.yml
scripts/deploy.sh

- 현재 배포되어 있는 버전 관리를 더 편하게 하기 위해, CD를 통한 배포 시, Docker 이미지에 버전 태그 추가함.

[NPG-150] 배포 이미지에 version 태그 추가

---

Jenkinsfile

- Jenkins에서 빌드 성공/실패 여부를 Discord 채널로 알려주도록 Webhook 설정

[NPG-150] Jenkins 빌드 및 배포 웹훅 설정

---

NangPaGo-fe/src/components/common/TopButton.jsx
NangPaGo-fe/src/components/login/SocialLoginButton.jsx
NangPaGo-fe/src/components/recipe/RecipeListContent.jsx
NangPaGo-fe/src/globals.css
NangPaGo-fe/src/pages/login/Login.jsx

[NPG-147] 로그인 페이지 UI/UX 개선

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/config/security/SecurityConfig.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
NangPaGo-fe/src/api/commentService.js
NangPaGo-fe/src/api/communityComment.js
NangPaGo-fe/src/api/myPage.js
NangPaGo-fe/src/components/profile/ItemList.jsx
NangPaGo-fe/src/hooks/useMyPageInfo.js
NangPaGo-fe/src/hooks/useTabData.js
NangPaGo-fe/src/pages/mypage/Profile.jsx

탭을 빠르게 전환시켰을 때 이전 데이터가 로드 되는 현상이 발생하여 수정

[NPG-145] 탭 전환시 이전 데이터 초기화 버그 수정

---

NangPaGo-fe/src/components/common/Header.jsx
NangPaGo-fe/src/components/community/Community.jsx
NangPaGo-fe/src/pages/community/CommunityList.jsx
NangPaGo-fe/src/pages/community/CreateCommunity.jsx
NangPaGo-fe/src/pages/community/ModifyCommunity.jsx

- 대상 액션: 뒤로 가기, 새로 고침, Header 내 페이지 이동
- 대상 페이지: 게시물 생성 페이지, 게시물 수정 페이지

[NPG-157] 게시글 작성 중 사용자 액션 차단

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/controller/CommunityCommentController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
NangPaGo-fe/src/api/communityComment.js

- 커뮤니티, 레시피 댓글 API 오타 수정
- comments -> comment

[NO-ISSUE] 댓글 관련 API Endpoint 오타 수정

---

NangPaGo-be/gradle.properties
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/community/controller/CommunityCommentController.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/controller/RecipeCommentController.java
NangPaGo-fe/src/api/communityComment.js

[NO-ISSUE] NangPago release/1.4.1 merge to main

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/handler/OAuth2SuccessHandler.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/common/util/JwtUtil.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/auth/service/TokenService.java
NangPaGo-be/src/test/java/com/mars/NangPaGo/provider/TestJwtProvider.java

서버가 발급시켜주는 Access token & Refresh token 에 "id"(User 테이블의 PK) 클레임 추가

[NPG-148] Access token & Refresh token에 id 클레임 추가

---

NangPaGo-fe/src/components/layout/header/Header.jsx

- `logo.png` 경로 관련 warning 로그가 계속해서 노출되고 있는 상태를 해결.

[NO-ISSUE] `logo.png` 관련 경고 로그 표출 해결

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/entity/Recipe.java
NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java

- toggleFavorite: 즐겨찾기가 이미 되었다고 가정하고, 실행 시 반환할 Dto를 생성하면서 즐겨찾기가 false된걸 확인합니다.
- isFavoriteByUser: 즐겨찾기 관련 데이터가 있다고 가정하고, 즐겨찾기가 true인지 확인합니다.

[NPG-74] 레시피 즐겨찾기 관련 서비스 테스트 코드 추가

---

NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentServiceTest.java

[NPG-74] 레시피 댓글 관련 테스트 코드 추가

---

NangPaGo-be/src/main/java/com/mars/NangPaGo/NangPaGoApplication.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/dto/RecipeCommentResponseDto.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/repository/RecipeCommentRepository.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/comment/recipe/service/RecipeCommentService.java
NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/UserService.java
NangPaGo-fe/src/common/modal/UpdateUserInfoModal.jsx
NangPaGo-fe/src/components/common/CreateButton.jsx
NangPaGo-fe/src/components/common/Footer.jsx
NangPaGo-fe/src/components/common/SubmitButton.jsx
NangPaGo-fe/src/components/layout/header/ProfileDropdown.jsx
NangPaGo-fe/src/components/profile/ItemList.jsx
NangPaGo-fe/src/components/profile/ProfileHeader.jsx
NangPaGo-fe/src/components/profile/ProfileTabs.jsx
NangPaGo-fe/src/pages/mypage/Modify.jsx
NangPaGo-fe/src/pages/mypage/Profile.jsx
NangPaGo-fe/src/pages/recipe/RecipeList.jsx
NangPaGo-fe/tailwind.config.js

마이페이지 반응형 구현 
탑버튼 영역으로 인해 터치가 안 되었던 버그 수정

[NPG-147] 마이페이지 UI/UX 개선 및 탑버튼 영역 수정

---

NangPaGo/NangPaGo-app/frontend/src/api/recipe.js
NangPaGo/NangPaGo-app/frontend/src/components/recipe/Recipe.jsx
NangPaGo/NangPaGo-app/frontend/src/components/recipe/RecipeListContent.jsx
NangPaGo/NangPaGo-app/frontend/src/components/search/EmptyState.jsx
NangPaGo/NangPaGo-app/frontend/src/components/search/NoResult.jsx
NangPaGo/NangPaGo-app/frontend/src/components/search/SearchInput.jsx
NangPaGo/NangPaGo-app/frontend/src/components/search/SearchResult.jsx
NangPaGo/NangPaGo-app/frontend/src/components/util/stringUtil.jsx
NangPaGo/NangPaGo-app/frontend/src/hooks/useRecipeSearch.js
NangPaGo/NangPaGo-app/frontend/src/pages/search/RecipeSearch.jsx

[NPG-147] 레시피 검색 UI 수정

---

NangPaGo/NangPaGo-app/frontend/src/components/common/CreateButton.jsx
NangPaGo/NangPaGo-app/frontend/src/components/community/Community.jsx
NangPaGo/NangPaGo-app/frontend/src/components/community/CommunityCard.jsx
NangPaGo/NangPaGo-app/frontend/src/components/community/FileUpload.jsx
NangPaGo/NangPaGo-app/frontend/src/components/community/TextArea.jsx
NangPaGo/NangPaGo-app/frontend/src/components/community/TextInput.jsx
NangPaGo/NangPaGo-app/frontend/src/pages/community/CommunityList.jsx
NangPaGo/NangPaGo-app/frontend/src/pages/community/CreateCommunity.jsx
NangPaGo/NangPaGo-app/frontend/src/pages/community/ModifyCommunity.jsx

- 커뮤니티 리스트 반응형으로 수정
- 글쓰기 버튼 색상 변경

[NPG-147] 커뮤니티 리스트 UI 수정

---

NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityLikeService.java
NangPaGo/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityLikeServiceTest.java
NangPaGo/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java

CommunityService Test코드 작성
CommunityLikeService Test코드 작성

[NPG-161] CommunityService Test코드 작성

---

NangPaGo/NangPaGo-app/frontend/src/components/community/Community.jsx
NangPaGo/NangPaGo-app/frontend/src/components/community/FileUpload.jsx
NangPaGo/NangPaGo-app/frontend/src/components/community/TextArea.jsx
NangPaGo/NangPaGo-app/frontend/src/components/community/TextInput.jsx
NangPaGo/NangPaGo-app/frontend/src/pages/community/CreateCommunity.jsx
NangPaGo/NangPaGo-app/frontend/src/pages/community/ModifyCommunity.jsx

[NPG-165] 커뮤니티 게시글 작성 및 수정 반응형 UI 개선

---

NangPaGo/NangPaGo-app/frontend/index.html
NangPaGo/NangPaGo-app/frontend/src/api/refrigerator.js
NangPaGo/NangPaGo-app/frontend/src/components/recipe/RecipeCard.jsx
NangPaGo/NangPaGo-app/frontend/src/components/refrigerator/AddIngredientForm.jsx
NangPaGo/NangPaGo-app/frontend/src/components/refrigerator/IngredientList.jsx
NangPaGo/NangPaGo-app/frontend/src/components/search/SearchInput.jsx
NangPaGo/NangPaGo-app/frontend/src/hooks/useRefrigerator.js
NangPaGo/NangPaGo-app/frontend/src/pages/refrigerator/Refrigerator.jsx
NangPaGo/NangPaGo-app/frontend/src/pages/search/RefrigeratorSearch.jsx
NangPaGo/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java

냉장고 및 추천레시피 UI 수정
먼저 레시피 검색 UI 수정 #215 리뷰해주세요.

[NPG-147] 냉장고 UI 수정

---

NangPaGo-client/src/pages/error/NotFound.jsx
NangPaGo-client/src/routes/Router.jsx

- 설정되지 않은 경로(`'*'`) 접근 시, `NotFound` 페이지로 이동

[NPG-166] 리액트에서 404 에러 처리 (NotFound 페이지 이동)

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/builder/EsRecipeSearchQueryBuilder.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsSynchronizerService.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/recipe/RecipeEs.java

좋아요 수, 댓글 수에 따라 검색결과 내림차순 정렬되어 반환하도록 하였습니다.
FunctionScore을 사용하였습니다.

[NPG-135]좋아요 수, 댓글 수에 따라 검색결과 내림차순 정렬하여 반환

---

NangPaGo-admin/package-lock.json
NangPaGo-admin/package.json
NangPaGo-admin/src/pages/Login.jsx
NangPaGo-admin/vite.config.js
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/NangPaGoAdminApplication.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/entrypoint/UnauthorizedEntryPoint.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/filter/AdminLogoutFilter.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/filter/JwtAuthenticationFilter.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/handler/AdminSuccessHandler.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/AdminLogoutService.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/UserDetailServiceImpl.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/vo/UserDetailsImpl.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/auth/repository/RefreshTokenRepository.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/auth/service/TokenService.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/auth/RefreshTokenDto.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/user/UserResponseDto.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/User.java

- #### 프로젝트 프론트 구조 변경에 맞춰 새로운 브랜치로 다시 작업했습니다.
- #### 테이블 변경사항이 있습니다.
- 유저 테이블에 관리자의 로그인을 위해 password를 추가했습니다.
- `ALTER TABLE userADD COLUMN password VARCHAR(255) NULL DEFAULT NULL AFTER left_at;`
- 현재 `NANGPAGO_DEV`, `NANGPAGO_TEST`에만 변경이 적용되어있습니다.
- #### 관리자 유저 데이터는 임시로 넣어두고 진행하였습니다.
- `localhost:5573`으로 접속 시 `/login`폼으로 이동하며, 로그인 시 유저 여부와 권한을 확인 한 뒤 `/dashboard`로 이동합니다.
- #### 현재 로그인 시 검증과 토큰 발급만 구현이 되어있습니다.

[NPG-167] 관리자 로그인 기능 구현

---

NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java

- 리액트를 포함하는 컨테이너 구조에서 필요했던 White list를 제거함.

[NO-ISSUE] 불필요한 White list 제거

---

NangPaGo-api/NangPaGo-app/src/main/resources/application.yml

- `test` profile의 `ddl-auto` 설정값을 `create-drop`으로 변경. 
- DB 스키마가 변경될 때 마다 `_TEST` DB에 항상 변경사항을 적용시켜줘야 하는 불편함을 해결하기 위해.

[NO-ISSUE] 테스트 코드 영역 - `ddl-auto` 설정값 변경

---

NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/UserDetailServiceImpl.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java

1. `PasswordEncoder`를 빈 등록하여 BCrypt암호화 및 복호화 가능하게 했습니다.
2. `UserDetailServiceImpl`에서` "{noop}" + user.getPassword()`으로 명시하여 암호화를 사용하지 않도록 했으나,
이 부분을 제거하여 암호화 되도록 하였습니다.

[NPG-167] 관리자 패스워드 암호화 추가

---

NangPaGo-api/NangPaGo-app/build.gradle
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQConfig.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumer.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationPublisher.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/SseEmitterService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeService.java
NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/exception/NPGExceptionType.java
NangPaGo-client/src/api/recipe.js
NangPaGo-client/src/hooks/useRecipeData.js
NangPaGo-client/src/slices/loginSlice.js

- RabbitMQ 의존성 추가 및 설정
- RabbitMQ와 SSE를 이용하여 사용자가 레시피 좋아요를 누르면 이벤트발생시켜 모든 사용자에게 실시간으로 좋아요 카운트 증가 및 감소를 확인 할 수 있게 함.

[NPG-169] 레시피 좋아요 카운트 수 실시간 반응 구현

---

NangPaGo-admin/src/pages/Login.jsx

- 관리자 로그인 시 로그인에 성공했다는 alert 삭제

[NPG-182] 불필요한 alert 제거

---

NangPaGo-admin/src/api/axiosInstance.js
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/component/auth/AuthenticationHolder.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/auth/controller/AdminAuthController.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/service/UserService.java
NangPaGo-api/NangPaGo-app/build.gradle
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQConfig.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumer.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationPublisher.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/SseEmitterService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeService.java
NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/exception/NPGExceptionType.java
NangPaGo-client/src/api/recipe.js
NangPaGo-client/src/hooks/useRecipeData.js
NangPaGo-client/src/slices/loginSlice.js

- 관리자가 로그인할 때  Access 토큰을 재발급하는 기능 추가

[NPG-177] 관리자 Access 토큰 재발급 기능 추가

---

NangPaGo-client/src/common/modal/FileSizeErrorModal.jsx
NangPaGo-client/src/components/community/Community.jsx
NangPaGo-client/src/components/community/comment/CommunityComment.jsx
NangPaGo-client/src/components/recipe/comment/CommentForm.jsx
NangPaGo-client/src/components/recipe/comment/CommentList.jsx
NangPaGo-client/src/components/recipe/comment/RecipeComment.jsx
NangPaGo-client/src/pages/community/CommunityDetail.jsx
NangPaGo-client/src/pages/search/RefrigeratorSearch.jsx

- 댓글 작성 시, 엔터를 입력하면 전송되도록 하는 기능을 제거하였습니다.
- 저장을 위해 반드시 "등록" 버튼을 클릭(또는 터치)하여야만 전송되도록 하였음.
- UI를 보다 가독성 좋게 개선했습니다.
- 개행 적용
- 수정/삭제 버튼 위치 depth +1
- 댓글 UI 개선사항
| **변경 전** | **변경 후**        |
|-----------------|---------------------------|
| <img width="789" alt="image" src="https://github.com/user-attachments/assets/986b90c1-1314-4b69-999b-a7d78967436e" /> | <img width="777" alt="image" src="https://github.com/user-attachments/assets/5862d6e1-c0db-41f2-b7e8-e172dd4ea916" /> |

[NPG-181] 댓글 작성 keypress 제거, 댓글 UI 개선

---

NangPaGo-admin/Dockerfile-admin-fe
NangPaGo-api/NangPaGo-admin/Dockerfile-admin-be
deploy/nangpago-admin/deploy.sh
docker/nangpago-admin/docker-compose.blue.yml
docker/nangpago-admin/docker-compose.green.yml
docker/nangpago-app/docker-compose.blue.yml
docker/nangpago-app/docker-compose.green.yml
jenkins/nangpago-admin/Jenkinsfile

- 냉파고 Admin 페이지에 대한 CI/CD 파이프라인 스크립트 추가

[NPG-185] Admin 페이지 Jenkins CI/CD 구성

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQConfig.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeLikeMessageDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeLikeResponseDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumer.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationPublisher.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/SseEmitterService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/repository/RecipeLikeRepository.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeMessageService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeService.java
NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumerTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeMessageServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeServiceTest.java
NangPaGo-client/src/hooks/useRecipeData.js

- 레시피 좋아요 기능을 RabbitMQ 기반 비동기로 처리하도록 변경함.

[NO-ISSUE] 레시피 좋아요 기능 비동기 처리

---

NangPaGo-admin/src/pages/Users.jsx

- Admin의 Users(사용자 관리) 페이지 화면을 기획했습니다.

[NPG-178] Admin 사용자 관리 페이지 화면 기획

---

NangPaGo-client/src/components/comment/Comment.jsx

- 댓글 작성 이후 자신이 작성한 댓글을 바로 확인할 수  있도록 1페이지로 이동하도록 하였습니다.

[NPG-193] 댓글 작성 이후 1페이지로 전환

---

NangPaGo-client/src/pages/search/RecipeSearch.jsx
NangPaGo-client/src/pages/search/RefrigeratorSearch.jsx

- 재료 검색 창의 뒤로가기 버튼 색상 수정했습니다.
- 레시피 검색 창에는 이상 없었습니다.
- 기존
> ![image](https://github.com/user-attachments/assets/1faa6aaf-3eea-48e6-bb43-0b572d33ea12)
- 변경
> ![image](https://github.com/user-attachments/assets/1d393bd3-efc5-46c1-8020-eb4f8bdc5689)

[NPG-194] 재료 검색창 뒤로가기 버튼 색 수정

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/dto/CommunityCommentResponseDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/dto/RecipeCommentResponseDto.java
NangPaGo-client/src/components/profile/ItemList.jsx

- `recipeId`가 아닌 레시피의 `commentId` 로 잘못 매핑되고 있었음
- 관련 **resposneDto**에서 `entityId`라는 이름의 `recipeId` 추가

[NPG-196] 마이페이지 댓글에서 Recipe ID 매핑 오류와 관련 Dto 수정

---

NangPaGo-client/src/components/profile/ItemList.jsx

[NPG-197] 마이페이지 댓글 내용에서 개행 문자 처리 추가

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-client/src/api/recipe.js
NangPaGo-client/src/hooks/useRecipeData.js

즐겨찾기 api에서 정상적으로 데이터를 받고 있지만 UI가 변화없었던 버그 수정
https://github.com/user-attachments/assets/24424e90-4d47-49ac-a940-41835be63d00

[NPG-192] 즐겨찾기 온오프UI 버그 수정

---

NangPaGo-admin/src/pages/Login.jsx
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java

- 관리자 페이지의 Login URI 에 `/api` prefix가 없어, 요청에 실패(404)하는 문제를 해결합니다.

[NO-ISSUE] 관리자 페이지 - Login URI 수정

---

NangPaGo-admin/src/api/usermanage.js
NangPaGo-admin/src/pages/Users.jsx
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/chart/controller/ChartController.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/controller/UserController.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/dto/UserDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/service/UserService.java

- 기존 UI에 유저를 조회하는 API를 추가하여 연결했습니다. 
- 기본 **조회 조건**으로 유저 `Role`이 `ROLE_ADMIN`이 아닌 경우로 하였습니다.
- 유저 조회 및 상태처리 Api 호출은 `usermanage.js`로 분리 후 `import`하여 사용하도록 했습니다.

[NPG-201] 관리자 유저 페이지 기능 추가

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/dto/CommunityCommentResponseDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/dto/RecipeCommentResponseDto.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/User.java
NangPaGo-client/src/components/comment/CommentList.jsx
NangPaGo-client/src/hooks/useRefrigerator.js

- 회원탈퇴 (softdelete)시, 기존 email + 기존 Id를 추가함으로 unique제약조건 유지하며 유저정보 변경 
- 회원탈퇴시, 닉네임 변경 ( 탈퇴한 회원 + 기존 Id ) -> recipeComment, CommunityComment 이메일 마스킹하여 보여주던 부분을 닉네임으로 보여주도록 수정 
- 테스트 코드 수정

[NPG-132] 유저 회원탈퇴 및 재가입 기능구현

---

NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/filter/JwtAuthenticationFilter.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/component/auth/AuthenticationHolder.java
NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/auth/filter/JwtAuthenticationFilterTest.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/handler/OAuth2SuccessHandler.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/web/HttpClientConfig.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/client/OAuth2ApiClient.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/repository/OAuthProviderTokenRepository.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/service/OAuth2ProviderTokenService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/service/TokenService.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/aop/auth/AuthenticationAspectTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/filter/JwtAuthenticationFilterTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/handler/OAuth2SuccessHandlerTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/service/OAuth2LogoutServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/vo/OAuth2RequestResolverTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/auth/service/OAuth2ProviderTokenServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/auth/service/TokenServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/provider/TestJwtProvider.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/service/TestService.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/support/IntegrationTestSupport.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/auth/OAuthProviderToken.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/User.java

- 지금까지 테스트 없이 작성했던 유틸, 서비스 클래스들에 대한 테스트를 추가합니다.
- 테스트 작성 과정에서 비효율 또는 불필요한 코드들에 대한 리팩터링을 진행했습니다.

[NO-ISSUE] 누락된 테스트 작성 및 관련 코드 리팩터링

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/dto/RecipeFavoriteListResponseDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/refrigerator/service/RefrigeratorServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user/service/UserServiceTest.java

- 누락되어 있던 Service 레이어에 대한 테스트 코드를 추가로 작성합니다.
- 작성 과정에서 일부 코드를 리팩터링했습니다.

[NO-ISSUE] 누락된 Service 레이어 테스트 코드 추가 작성

---

NangPaGo-admin/vite.config.js
NangPaGo-client/vite.config.js

- Vite 6.x 버전에서 요구하는 allowHosts 설정값을 추가합니다.
- 보안 관련 이슈로 인해 버전 업그레이드를 진행하였음.

[NO-ISSUE] Vite 6.x 버전 관련 이슈 해결

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/CommunityResponseDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityRepository.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/user/MyPageDto.java
NangPaGo-client/src/api/myPage.js
NangPaGo-client/src/components/profile/ItemList.jsx
NangPaGo-client/src/components/profile/ProfileTabs.jsx
NangPaGo-client/src/hooks/useMyPageInfo.js
NangPaGo-client/src/hooks/useTabData.js

- 마이페이지 게시글 api 및 프론트 구현
- 테스트 유저 생성 코드 변경 
- 이유: 기존 코드에선 이메일을 api 응답으로 주고 있어 nickname으로 변경해서 변경하였습니다.

[NPG-200] 마이페이지 게시글 탭 구현

---

NangPaGo-client/src/components/button/SliderArrowButton.jsx
NangPaGo-client/src/components/layout/header/Header.jsx
NangPaGo-client/src/components/recipe/CookingStepsSlider.jsx

- 기존에 있던 컴포넌트에 맞춰서 함수 분리 및 코드 리팩토링
- components/recipe/CookingStepsSlider.jsx 에 작성했던 `ArrowButton(){}`을 components/button/SliderArrowButton.jsx로 리팩토링
- 화살표를 조금 더 크게 보이도록 수정함	
- 화살표 크기는 2xl -> 4xl로 수정
- 배경 버튼크기는 `w-11 h-11` ->` w-14 h-14`로 수정
- 배경 이미지에 따라 잘 안보이는 경우가 있어서, opacity(불투명도)를 높임
- 투명도를 `bg-white/20` 에서 `bg-white/50`으로 변경
- 첫번째 페이지일때는 왼쪽 화살표가 사라지게 하고, 마지막 페이지일때는 오른쪽 화살표가 사라지도록 수정

[NPG-218] 레시피 상세 - 조리과정 슬라이더 기능 및 UI 개선

---

NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/UserDetailServiceImpl.java
NangPaGo-api/NangPaGo-admin/src/main/resources/application.yml
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeLikeSseDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeEventListener.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/event/RecipeLikeSseService.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/auth/handler/OAuth2SuccessHandlerTest.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/user/UserResponseDto.java
NangPaGo-client/src/hooks/usePostStatus.js
NangPaGo-client/src/slices/loginSlice.js

- 레시피 좋아요 SSE 수신으로 인한 값 변경 이벤트에 대한 로직 개선
- 사용자 자신이 발생시킨 SSE 이벤트에 대해서는 값을 업데이트 하지 않도록 변경
- 리액트의 전역 상태값으로 `userId` 를 보관하고 있도록 개선

[NO-ISSUE] 레시피 좋아요 SSE UI 업데이트 버그 픽스

---

NangPaGo-client/src/pages/common/DetailPage.jsx

- 'recipe'의 경로는 `/`인데, `/recipe`로 리다이렉트 되고 있었음.

[NO-ISSUE] FIX - 레시피 리다이렉트 경로 버그 수정

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/repository/CommunityCommentRepository.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/service/CommunityCommentService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/controller/RecipeCommentController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/repository/RecipeCommentRepository.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/service/RecipeCommentService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityRepository.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/community/service/CommunityCommentServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/page/PageRequestVO.java
NangPaGo-client/src/api/comment.js
NangPaGo-client/src/api/community.js
NangPaGo-client/src/api/post.js
NangPaGo-client/src/components/comment/Comment.jsx
NangPaGo-client/src/components/comment/CommentList.jsx
NangPaGo-client/src/hooks/useCommentsData.js

- 댓글 페이지네이션 공통 VO 적용
- PageRequestVO 수정
- 댓글 API 는 페이지 사이즈 5개씩 요청을 하는데 디폴트 값인 12씩 들어와서 수정

[NPG-163] 댓글 페이지네이션 공통 VO 적용

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/service/CommunityCommentService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/controller/RecipeCommentController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/service/RecipeCommentService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/community/service/CommunityCommentServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user/service/UserServiceTest.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/dto/page/PageResponseDto.java

- PageDto -> PageResponseDto 클래스명 변경

[NO-ISSUE] PageDto 클래스명 변경

---

NangPaGo-client/src/components/layout/header/Header.jsx
NangPaGo-client/src/components/layout/header/NavItem.jsx

[NO-ISSUE] UI 수정 - Header 아이콘 디자인 통일

---

NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/entrypoint/UnauthorizedEntryPoint.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/entrypoint/UnauthorizedEntryPoint.java

- 액세스 토큰 재발급을 위해서 401 을 내려주도록 변경함. (기존 코드를 실수로 400으로 고쳤었음)

[NO-ISSUE] 액세스 토큰 재발급 버그 픽스

---

NangPaGo-api/NangPaGo-admin/gradle.properties
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/entrypoint/UnauthorizedEntryPoint.java
NangPaGo-api/NangPaGo-app/gradle.properties
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/entrypoint/UnauthorizedEntryPoint.java

- app v1.8.1, admin v0.2.1 릴리즈

[NO-ISSUE] NangPago release/1.8.1 merge to main

---

NangPaGo-client/package-lock.json
NangPaGo-client/package.json
NangPaGo-client/postcss.config.js
NangPaGo-client/vite.config.js

- 아이폰 사파리 브라우저로 `nangpago.site` 에 접속하면, 로딩이 오래 걸리고 최종적으로 흰 화면만 보이는 현상이 계속 지속됨.
- 맥북 사파리는 이상 무
- 정확한 원인 파악이 안되는 관계로, 우선 GPT가 알려준 수정 방법을 적용해서 버그 픽스를 시도함.

[NO-ISSUE] Mobile 사파리 화면 안열리는 버그 픽스 시도

---

NangPaGo-admin/src/api/usermanage.js
NangPaGo-admin/src/pages/Users.jsx
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/controller/UserController.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/service/UserService.java
NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/user/service/UserServiceTest.java

- `UserStatus`와 `OAuth2Provider`를 기준으로 조건을 추가 했습니다.
- 필터 조건과 기존 정렬 기능을 같이 사용할 수 있도록 하면서, 기존 `getUserList`메서드에 필터 조건 파라미터를 추가하여 사용하도록 수정했습니다.
> 
- 필터 조건을 추가한 테스트 코드 추가했습니다.

[NPG-203] 어드민 페이지 유저 조회 필터 조건 추가

---

NangPaGo-admin/src/api/audit.js
NangPaGo-admin/src/pages/Audit.jsx
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/swagger/SwaggerConfig.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/controller/AuditLogController.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/dto/AuditLogResponseDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/service/AuditLogService.java

- 수집된 감사 로그를 단순 조회할 수 있게 기능을 추가합니다.
- SwaggerUI 관련 Config를 추가합니다.

[NPG-232] Admin 감사 로그 조회 기능 추가

---

NangPaGo-admin/src/App.jsx
NangPaGo-admin/src/api/audit.js
NangPaGo-admin/src/components/DashboardLayout.jsx
NangPaGo-admin/src/pages/Audit.jsx
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/dto/AuditLogResponseDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/service/AuditLogService.java
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/enums/audit/AuditActionType.java

- 로그 테이블의 행을 클릭하면 확장 -> 로그의 상세 정보를 볼 수 있게 개선

[NPG-232] 감사 로그 기능 수정 - 로그 상세 정보 보기

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserNotificationController.java

- 유저 알림 SSE 구독 요청시, 쿠키에 Access 토큰이 없는 경우에 대한 예외 처리 코드를 추가합니다.

[NO-ISSUE] 유저 알림 SSE 구독 - Access 토큰 예외 처리

---

NangPaGo-client/src/components/modal/UpdateUserInfoModal.jsx

닉네임 변경 후, UpdateUserInfoModal.jsx 모달에서 확인버튼을 누르면 /my-page로 리다이렉션 되도록 수정

[NPG-235] 닉네임 변경 후 마이페이지로 리다이렉션

---

NangPaGo-client/src/api/recipe.js
NangPaGo-client/src/api/refrigerator.js
NangPaGo-client/src/api/userRecipe.js
NangPaGo-client/src/components/community/CommunityListContent.jsx
NangPaGo-client/src/components/recipe/RecipeListContent.jsx
NangPaGo-client/src/hooks/useRefrigerator.js
NangPaGo-client/src/pages/refrigerator/Refrigerator.jsx
NangPaGo-client/src/routes/AuthenticatedRoute.jsx
NangPaGo-client/src/routes/Router.jsx

- 기존 hasMoreRecipes가 마지막 페이지가 아님에도 불구하고 true로 고정되어 무한스크롤이 되지 않음 
- 응답 데이터 last 이용해서 수정

[NPG-237] 내 냉장고 무한스크롤 버그 수정

---

NangPaGo-client/src/common/styles/ListPage.js
NangPaGo-client/src/components/button/RecipeButton.jsx
NangPaGo-client/src/components/community/Community.jsx
NangPaGo-client/src/components/community/CommunityCard.jsx
NangPaGo-client/src/components/profile/ItemList.jsx
NangPaGo-client/src/components/recipe/Recipe.jsx
NangPaGo-client/src/components/recipe/RecipeCard.jsx
NangPaGo-client/src/components/recipe/RecipeInfo.jsx
NangPaGo-client/src/components/recipe/RecipeListTab.jsx
NangPaGo-client/src/components/refrigerator/IngredientList.jsx
NangPaGo-client/src/components/search/SearchBar.jsx
NangPaGo-client/src/components/search/SearchInput.jsx
NangPaGo-client/src/components/userRecipe/UserRecipeCard.jsx
NangPaGo-client/src/pages/search/RecipeSearch.jsx
NangPaGo-client/src/pages/search/RefrigeratorSearch.jsx

- 사이트 전체적으로 가독성을 해칠법한 요소를 찾아서 개선해보려고 합니다.
- 사용하는 색깔의 종류에 관해
- 한 사이트에 너무 많은 종류의 색깔을 사용하면 가독성을 해친다고 생각하였습니다.
그래서 사용하는 **색상의 종류는 줄이고,** 가독성을 위해서 필요한 곳에 적절하게 **대비**를 적용해보았습니다.
- 참고한 아티클:
- [Brunch - 색상 디자인 적용 Tips](https://brunch.co.kr/@ebprux/153)
|Before|After|
|---|---|
|<img width="340" alt="image" src="https://github.com/user-attachments/assets/dd1814a3-1481-4d3c-8c1e-c1ce8290f2aa" />|<img width="341" alt="image" src="https://github.com/user-attachments/assets/fca74b44-f924-4203-8a8f-9ee182851141" />|
|<img width="656" alt="image" src="https://github.com/user-attachments/assets/5aee14b9-38f5-4a3d-8f3f-e0ab4535f61e" />|<img width="669" alt="image" src="https://github.com/user-attachments/assets/7fc8980b-f477-45c5-93e1-8027fbedc9b8" />|

[NO-ISSUE] 전반적인 UI 개선 - `secondary` color 사용 지양

---

NangPaGo-client/src/components/button/RecipeButton.jsx
NangPaGo-client/src/components/community/Community.jsx
NangPaGo-client/tailwind.config.js

- 레시피 및 커뮤니티 좋아요 기능에 대한 바운스 & 카운트 애니메이션을 적용합니다.

[NO-ISSUE] 좋아요 - 바운스 & 카운트 애니메이션 추가

---

NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/dashboard/service/ChartServiceTest.java

- 데이터 그래프 바가 최소 4개 이상 보일 수 있도록 수정
>

[NPG-246]  관리자 페이지 그래프 최소 개수로 보이도록 개선

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/dto/UserRecipeResponseDto.java
NangPaGo-client/src/components/community/Community.jsx
NangPaGo-client/src/components/userRecipe/UserRecipeDetail.jsx

- 수정 전: 커뮤니티(작성자 닉네임이 안보임) & 유저레시피(작성자와 수정날짜 안보임)
- 수정 후: title 밑에 작성자(nickname)와 수정날짜(updatedAt)가 한줄에 보이도록 수정

[NPG-243] 커뮤니티 & 유저 레시피 - 작성자 닉네임 추가

---

NangPaGo-api/NangPaGo-app/gradle.properties

[NO-ISSUE] NangPago release/1.10.1 merge to main 

---

NangPaGo-admin/src/App.jsx
NangPaGo-admin/src/api/axiosInstance.js
NangPaGo-admin/src/components/common/AuthErrorPage.jsx
NangPaGo-admin/src/components/common/Modal.jsx
NangPaGo-admin/src/components/modal/AuthErrorModal.jsx
NangPaGo-admin/tailwind.config.js
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/handler/AdminSuccessHandler.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/AdminLogoutSuccessHandler.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/security/SecurityConfig.java

- 기존 관리자 JWT 사용하던 부분 삭제 이후 세션 방식으로 수정하였습니다.
- 세션 방식으로 수정하면서 401에러를 처리하던 인터셉터를 모달 창을 표시하는 페이지로 이동 시키도록 수정하였습니다.
JSESSIONID가 없거나, 임의로 주소 값을 입력하여 접근하였을 때 모달 페이지로 이동합니다.
>

[NPG-242] 관리자 세션 방식으로 변경

---

NangPaGo-client/src/components/button/ToggleButton.jsx

| **[작성]** 아이콘 | **[작성/수정/삭제]** 아이콘 |
|:---------------------:|:---------------------:|
| <img width="77" alt="image" src="https://github.com/user-attachments/assets/6fbcddea-2879-4a05-891f-5a75b68ca037" />  |  <img width="77" alt="image" src="https://github.com/user-attachments/assets/a3899c3b-456b-49ea-9452-d81076658889" /> |

[NO-ISSUE] 토글 버튼 (작성, 작성/수정/삭제) 아이콘 변경

---

NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/security/SecurityConfig.java
NangPaGo-api/NangPaGo-admin/src/main/resources/application.yml
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/repository/UserRecipeLikeRepository.java

- Admin 세션 타임아웃을 설정 및 기타 세션 인증 방식에 대한 추가 보안 설정
- 기타: 유저 레시피 좋아요 find Lock 해제 (이전 PR에서 수정했어야 하는데 누락)

[NO-ISSUE] Admin 세션 타임아웃 설정

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/message/UserNotificationMessageConsumer.java
NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user_recipe/service/UserRecipeServiceTest.java

- 내가 작성한 게시글에 좋아요, 댓글 작성 시 알림이 발송&수신 되던 문제를 해결합니다.
- Firebase 와 관련된 테스트 코드가 잘못되어 있던 부분을 함께 수정합니다.

[NPG-252] 자기 자신의 게시글에 대한 활동에는 알림 발송 방지

---

NangPaGo-client/src/components/common/ContentCard.jsx
NangPaGo-client/src/components/community/CommunityListContent.jsx

- 커뮤니티, 유저 레시피 상세페이지 진입 시 잘못된 URI로 네비게이션을 시도하는 버그를 수정합니다.

[NO-ISSUE] 커뮤니티, 유저 레시피 네비게이션 버그 수정

---

NangPaGo-client/src/components/refrigerator/AddIngredientForm.jsx

- 내 냉장고 재료 검색창의 UI를 개선했습니다.
- 검색 창 내의 텍스트 변경 및 돋보기 아이콘 추가
- 검색 창 마우스 드래그 시 버튼에 드래그 하듯이 손모양 커서가 나오도록 수정
|변경전|변경후|
|------|------|
|![image](https://github.com/user-attachments/assets/830582d5-244b-4dce-b098-65034373985b)|![image](https://github.com/user-attachments/assets/13a83f4f-8719-4041-8dad-5016fe6f8128)|

[NPG-254] 내 냉장고 재료 검색창 UI 개선

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeSearchResponseDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeEsService.java
NangPaGo-client/src/api/recipe.js
NangPaGo-client/src/components/community/CommunityListContent.jsx
NangPaGo-client/src/components/recipe/RecipeListContent.jsx
NangPaGo-client/src/components/search/SearchResult.jsx
NangPaGo-client/src/components/userRecipe/UserRecipeListContent.jsx
NangPaGo-client/src/hooks/useRecipeSearch.js
NangPaGo-client/src/pages/refrigerator/Refrigerator.jsx
NangPaGo-client/src/pages/search/RecipeSearch.jsx

[NPG-247] RecipeSearch Keyword검색시, Dto를 분리하여 최소값만 반환하도록 구현

---

NangPaGo-client/src/components/userRecipe/CookingStepCard.jsx
NangPaGo-client/src/components/userRecipe/CookingSteps.jsx
NangPaGo-client/src/components/userRecipe/CookingStepsSlider.jsx
NangPaGo-client/src/components/userRecipe/UserRecipe.jsx

- 이미지 리사이징 시, `object-contain` - 이미지가 크롭되지 않고, 원본 이미지 비율이 유지
- 재료 계량 없을 시, default 값('-') 설정 
<br>

[NPG-245] UI 개선 - 유저 레시피 상세 페이지

---

NangPaGo-client/src/api/recipe.js
NangPaGo-client/src/api/refrigerator.js
NangPaGo-client/src/components/common/ContentCard.jsx
NangPaGo-client/src/hooks/useRefrigerator.js
NangPaGo-client/src/pages/refrigerator/Refrigerator.jsx

[NO-ISSUE] 냉장고에서 식재료 검색시, 렌더링 해오지 못하는 문제 해결

---

NangPaGo-admin/src/pages/Users.jsx
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/dto/UserDetailResponseDto.java

[NPG-259] Admin - 사용자관리 table의 생년월일, 전화번호 column 제거

---

NangPaGo-admin/src/common/styles/CommonButton.js
NangPaGo-admin/src/pages/Users.jsx

- 검색창 위치 하단 가운데 -> **우상단**(체크박스 기준 우하단)으로 변경

[NPG-258] Admin - 사용자 검색창 위치 및 버튼 색상 변경

---

NangPaGo-client/src/hooks/useRefrigerator.js

/recommendations 가 아닌 /refrigerator이 호출되어 동기화가 안되던 문제 해결

[NO-ISSUE] 냉장고 추천레시피에서 잘못된 api가 호출되던 문제 해결

---

NangPaGo-client/src/hooks/useRefrigerator.js

/refrigerator 에서 재료 체크 후, 추천레시피로 이동한 후, 돌아가기 버튼을 눌렀을때, 
refrigerator이 호출되어야하나, Recommendations가 호출되는 현상 
재료 선택 후, 추천레시피로 이동시, Page 2를 건너뛰고 1번과 3번이 나오는 현상 
수정완료

[NO-ISSUE] Refrigerator 잘못된 api호출되던 현상

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/dto/UserNotificationSseDto.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/event/UserNotificationEventListener.java

- 기존 유저 알림 SSE 메시지에 포함되어 있던 불필요한 메시지를 제거합니다.
- 배포 서버에서 SSE가 동작하지 않는 버그 원인 파악을 위해 로그를 수집합니다.

[NO-ISSUE] 배포 서버 SSE 이슈 원인 파악을 위한 로그 수집

---

NangPaGo-client/src/components/layout/header/Header.jsx

- Header.jsx 에서 구독하는 유저 알림 SSE 연결에 대한 로직을 강화합니다.
- 정상 작동 여부는 모니터링 필요

[NO-ISSUE] SSE 연결 로직 개선 (모니터링 필요)

---

NangPaGo-admin/src/pages/Dashboard.jsx
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/HourlyUserActionCountDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java

- 최근 30일 기준, `AuditLog`를 기준으로 사용자 행동 분석 차트 구현

[NPG-257] 어드민 페이지 - 시간대별 사용자 활동 분석 차트 구현

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseStorageService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipe.java
NangPaGo-client/src/components/userRecipe/ManualInput.jsx
NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx
NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx

- 유저 레시피의 매뉴얼 이미지를 생성 & 수정 할 때 순서가 섞이거나 서버 에러가 발생하는 부분을 해결합니다.

[NO-ISSUE] 유저 레시피 매뉴얼 이미지 업로드 버그 수정

---

NangPaGo-client/src/hooks/useRefrigerator.js

- 냉장고 레시피 추천 - 상세 페이지 접속 후 뒤로 돌아올때 검색결과 초기화되는 문제를 해결합니다.

[NO-ISSUE] 냉장고 레시피 추천 - 상세 페이지 접속 후 뒤로 돌아올때 검색결과 초기화되는 문제

---

NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx

- 프론트에서 `formData`로 리스트를 전달하던 부분에 `null`값도 포함되게 하여,
리스트의 인덱스와 이미지 순서가 일치하도록 수정했습니다.

[NO-ISSUE] 유저 레시피 작성 이미지 순서 맞도록 수정

---

NangPaGo-admin/src/pages/Audit.jsx
NangPaGo-admin/src/pages/Dashboard.jsx
NangPaGo-admin/src/pages/Users.jsx
NangPaGo-api/NangPaGo-admin/gradle.properties
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/HourlyUserActionCountDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
NangPaGo-api/NangPaGo-app/gradle.properties
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseStorageService.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
NangPaGo-api/NangPaGo-app/src/main/resources/application.yml
NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipe.java
NangPaGo-client/src/components/layout/header/Header.jsx
NangPaGo-client/src/components/userRecipe/ManualInput.jsx
NangPaGo-client/src/hooks/useRefrigerator.js
NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx
NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx

- app v1.13.0, admin v1.3.0 릴리즈

[NO-ISSUE] NangPago release/1.13.0 merge to main

---

NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx

- 조리과정 추가 이후 이미지를 업로드해도 기본 이미지로 들어가던 부분 수정했습니다.
- `step${manual.step}_${file.name}` 대신 `step${index + 1}_${file.name}`로 변경하여, 
`manual.step`이 실제 단계와 일치하지 않을 수 있던 부분을 수정했습니다.

[NO-ISSUE] 유저 레시피 수정하면서 조리과정 추가 시 이미지 업로드 안되던 버그 수정

---

NangPaGo-admin/src/components/util/dashboardUtils.jsx
NangPaGo-admin/src/pages/Dashboard.jsx
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/HourlyUserActionCountDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java

- 기존: 시간대별 모든 액션의 총합을 시각화
- 변경: 액션별로 그룹화하여 시간대별 활동 빈도수 시각화
| **변경전** | **변경 후** |
|------------|-------------|
| <img width="360" alt="image" src="https://github.com/user-attachments/assets/4d29a306-a7ab-4915-9b09-3a3fc454f16a" /> | <img width="360" alt="image" src="https://github.com/user-attachments/assets/08cb1ff8-c030-4019-91cf-60e972a5f10d" /> |
- **util 함수 분리**:
- `processDailyUserStats`: 일별 통계에서 누락된 날짜를 0으로 채워 반환. (일일 접속자 통계)
- `getTodayData`: 오늘 날짜에 해당하는 통계 데이터를 반환. (일일 접속자 통계)
- `groupDataByAction`: 액션별로 데이터를 그룹화하여 분석. (시간대별 사용자 활동 분석)

[NPG-257] 개선 - 어드민 페이지에서 사용자 활동 분석 개선 (액션별 시간대 빈도수)

---

NangPaGo-admin/src/components/util/dashboardUtils.jsx
NangPaGo-admin/src/pages/Dashboard.jsx
NangPaGo-api/NangPaGo-admin/gradle.properties
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/audit/repository/AuditLogRepository.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/HourlyUserActionCountDto.java
NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
NangPaGo-api/NangPaGo-app/gradle.properties
NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx

- app v1.14.0, admin v1.4.0 릴리즈

[NO-ISSUE] NangPago release/1.14.0 merge to main

---

NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityRepository.java
NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/repository/UserRecipeRepository.java
NangPaGo-client/src/components/button/SubmitButton.jsx
NangPaGo-client/src/pages/community/CreateCommunity.jsx
NangPaGo-client/src/pages/community/ModifyCommunity.jsx
NangPaGo-client/src/pages/userRecipe/CreateUserRecipe.jsx
NangPaGo-client/src/pages/userRecipe/ModifyUserRecipe.jsx

- 글 작성 버튼을 중복 클릭하면 중복된 요청이 들어가는 문제를 해결합니다.

[NO-ISSUE] 글 작성 버튼 중복 클릭 방지
