- NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomLogoutFilter.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomSuccessHandler.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/CustomLogoutService.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/TokenService.java
> 로그아웃 로직을 필터에서 서비스계층으로 옮겨 수정
> 필터에서 트랜잭션을 걸면 시큐리티 필터에서 `GenericFilterBean` 얘를 초기화를 못시킴
> JPA의 remove 는 항상 트랜잭션을 필수로 해주어야 함
> [NO-ISSUE] 로그아웃 트랜잭션을 서비스계층으로 따로 분리하여 수정

- NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientElasticController.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/Ingredient.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/entity/IngredientElastic.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/repository/IngredientElasticRepository.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientElasticSearchService.java
- NangPaGo-be/src/main/resources/elastic/ingredient/post-mapping.json
- NangPaGo-be/src/main/resources/elastic/ingredient/post-setting.json
- Prefix 기준으로 검색
- 예시 `GET http://localhost:8080/ingredient/search?keyword=버`
```json
[
{ "id": 235,
"name": "녹인 무염 버터" },
{ "id": 598,
"name": "무염 버터" },
{ "id": 709,
"name": "버거빵" },
{ "id": 710,
"name": "버섯가루" },
{ "id": 711,
"name": "버섯마늘소금" },
{ "id": 712,
"name": "버터" },
{ "id": 841,
"name": "새송이 버섯" },
{ "id": 1045,
"name": "양송이 버섯" }
]
```
- 두 번 API 호출 문제: Elasticsearch 검색 쿼리가 반환되기 전에 API 호출이 이루어져 정확한 답변이 나오지 않음.
- Total Hits Value 로 **디버깅**한 결과, 첫번째 호출 때는 쿼리 그대로 반환되고 있음을 확인
```
Total Hits Value's Count(첫번째 호출): 1646
Total Hits Value's Count(두번째 호출): 4
```
- 동기/비동기 방식 검토 필요: 현재 동기/비동기 처리 방식에 대한 검토가 필요.
- _refresh 관련: 테스트 결과, _refresh 설정은 의미가 없음.
- `ElasticsearchConfig` 파일 삭제 예정: `application.yml`에서 설정한 `spring.elasticsearch.uris`와 중복되므로, 해당 파일은 삭제해도 정상 실행됨.
- 초성/중성/종성 검색 개선: 사용자가 …
> [NPG-46] 재료사전 search API 구현

- NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/controller/TokenController.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/dto/RefreshTokenDto.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/entity/RefreshToken.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/repository/RefreshTokenRepository.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/service/TokenService.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/util/JwtFilter.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/jwt/util/JwtUtil.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomSuccessHandler.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/service/CustomLogoutService.java
- 기존처럼 `user` 도메인 하위에 token 관련 코드가 있는게 어색하지는 않은 것 같지만, token 관련 코드가 많아지면서 도메인 개념이 섞이는 것 같아 분리해보았습니다.
- 참고: https://github.com/MARS-LIKELION/NangPaGo/pull/49 PR이 먼저 merge 된 다음 리뷰가 진행되어야 합니다.
[NPG-69]: https://mars-likelion.atlassian.net/browse/NPG-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [NPG-69] Token 관련 코드를 `jwt` 도메인 하위로 이전

- .github/workflows/cicd.yml
- NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/GlobalExceptionHandler.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/config/SecurityConfig.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/auth/CustomLogoutFilter.java
- NangPaGo-fe/src/components/common/Header.jsx
- 프론트에서 logout 요청 시 호출하는 URL에 `/api` 접두어가 빠져있어 요청을 실패하는 문제를 해결하기 위해 접두어 추가
- 그외 변경 사항 반영
- global exception handler에서 예외 로그 출력 시, 딱히 의미없이 표시되고 있던 정보를 예외 메시지로 변경
- 배포 Deploy 시 미사용 Docker image 삭제해주는 명령어가 동작하지 않고 있어, 옵션을 변경.
> [Npg-77] logout 요청 URL `/api` 접두어 추가

- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/controller/IngredientEsController.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/ingredient/service/IngredientEsSynchronizer.java
- NangPaGo-be/src/main/resources/elastic/ingredient/post-setting.json
- NangPaGo-data/elastic/ingredients_dictionary/init_index_ingredients_dictionary.sh
- ElasticSearch 검색 고도화
- 대소문자 구분 없는 검색 활성화
- MySQL-ES 업로드할 시, 기존 데이터 삭제
- keyword 파라미터 처리 방식 수정 (optional with default value '')
- 기존의 코드는 빈 값이 들어가면, API 호출 자체가 안 되었으나, 현재는 빈 배열이 나오는 형태로 변경
> [NPG-72] ElasticSearch 검색 고도화

- NangPaGo-be/src/test/java/com/mars/NangPaGo/domain/recipe/service/RecipeLikeServiceTest.java
- NangPaGo-be/src/test/java/com/mars/NangPaGo/provider/TestJwtProvider.java
- NangPaGo-be/src/test/java/com/mars/NangPaGo/support/IntegrationTestSupport.java
- 테스트 코드에서 임의의 인증된 Access Token을 발급할 수 있는 기능 추가
- `IntegrationTestSupport` 를 사용하는 Service 레이어 테스트 시 사용
- RecipeLikeService 테스트 케이스 추가
> [NO-ISSUE] Service 레이어 테스트 유틸리티 구조 개선 (인증 관련)

- NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/factory/userinfo/NaverUserInfo.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/dto/UserRequestDto.java
- NangPaGo-fe/src/common/modal/UpdateUserInfoModal.jsx
- NangPaGo-fe/src/components/common/Header.jsx
- NangPaGo-fe/src/components/mypage/UserInfoModify.jsx
- NangPaGo-fe/src/routes/Router.jsx
- 기존 구현 UI에 연동 계정 종류(구글,네이버) 제거
- alert부분을 메세지로 변경
- 닉네임 중복 체크 확인여부로 회원 정보 수정 버튼 비활성화 및 마진 위치 변경
- 회원 정보 가져오기, 중복 닉네임 검사, 회원 정보수정 API 연결
- 회원 정보 수정 버튼 클릭 시 나올 모달창 추가
> [NPG-92] 회원 정보 수정 페이지 UI 일부 수정,  API 연결, 모달 창 추가

- NangPaGo-fe/src/hooks/useDebounce.js
- NangPaGo-fe/src/pages/search/RecipeSearch.jsx
- NangPaGo-fe/src/pages/search/RefrigeratorSearch.jsx
- AS-IS
- 식재료 검색, 레시피 검색 UI의 자동완성을 위해 `keyDown()` 이벤트가 발생할 때 마다 즉시 API를 요청.
- **서버 부하 증가**
- TO-BE
- 0.5초 Debounce 기능을 적용하여, 사용자의 입력이 끝난 후 0.5초 뒤에 한번만 요청이 나가도록 변경, 서버 부하 감소
> [NPG-116] 검색 UI Debounce 적용

- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/dto/RecipeEsResponseDto.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/service/RecipeEsService.java
- NangPaGo-fe/src/api/commentService.js
- NangPaGo-fe/src/components/recipe/RecipeCard.jsx
- count 조회를 위해 과도하게 API를 요청하지 않도록, recipe search API 응답에 좋아요 및 댓글 개수를 추가.
> [NPG-127] 레시피 리스트 응답에 좋아요, 댓글 집계 추가

- NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/NPGExceptionType.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/recipe/controller/RecipeController.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/user/controller/UserController.java
- NangPaGo-fe/src/pages/mypage/Profile.jsx
- 마이페이지 하단 탭 전환 시, `pageNo` 값을 잘못 넣어서 조회하는 버그를 수정함.
- 탭 전환 이벤트에 debounce 를 먹여서, 빠르게 여러 탭을 전환해도 마지막 한번만 요청이 나가도록 하였음.
> [NO-ISSUE] 마이페이지 탭 조회 버그 수정

- NangPaGo-fe/src/components/common/Image.jsx
- NangPaGo-fe/src/components/community/Community.jsx
- NangPaGo-fe/src/components/community/CommunityCard.jsx
- NangPaGo-fe/src/components/community/FileUpload.jsx
- NangPaGo-fe/src/components/recipe/CookingSteps.jsx
- NangPaGo-fe/src/components/recipe/Recipe.jsx
- NangPaGo-fe/src/components/recipe/RecipeCard.jsx
- NangPaGo-fe/src/pages/community/CommunityList.jsx
- 이미지 클래스 타입 공통화: `components/common/Image.jsx`
```jsx
export const styles = {
imageList: 'w-full h-48 object-cover', // 조회 페이지의 경우, 고정된 height 값
mainImage: 'w-full h-full rounded-md', // 상세 페이지의 경우, 이미지 원본 그대로
detailImage: 'w-full h-full mb-6 rounded-md', // 상세 페이지의 경우, 이미지 원본 그대로
};
```
- 렌더링 로직 분리: `components/community/CommunityCard.jsx` 생성하여 레이아웃 처리
> [NPG-134] 메인과 상세 뷰의 이미지 레이아웃 통일

- NangPaGo-fe/src/components/community/FileUpload.jsx
- NangPaGo-fe/src/pages/community/CreateCommunity.jsx
- NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
1. `e.preventDefault()` 추가: <label> 클릭 시 기본 파일 선택 동작을 방지.
2. (BUG) 기본 이미지 미표시: 게시물 수정 시 `imagePreview`가 `null`이면 기본 이미지가 표시되지 않도록 처리.
3. (BUG) 파일 변경 시 상태 업데이트: `selectedFile !== file`로 파일 변경 시에만 상태를 업데이트하여 불필요한 렌더링을 방지.
> [NPG-149] 커뮤니티 게시물: 이미지 취소 버튼 추가

- NangPaGo-be/src/main/java/com/mars/NangPaGo/common/exception/GlobalExceptionHandler.java
- NangPaGo-be/src/main/java/com/mars/NangPaGo/domain/community/controller/CommunityController.java
- NangPaGo-fe/src/api/community.js
- NangPaGo-fe/src/pages/community/CreateCommunity.jsx
- NangPaGo-fe/src/pages/community/ModifyCommunity.jsx
기존에는 예외처리는 되어있으나 맞지않는 에러문구를 보여주었고,
그래서 백엔드에서 알맞는 에러문구를 보내주고, 프론트에 그대로 보여줄 수 있도록 하였습니다.
컨트롤러의 `@Valid`된 Dto의 validation 관련 어노테이션의 메시지를 가져와 프론트에서 보여주도록 했습니다.
> [NPG-140] 커뮤니티 게시글 예외 발생 메시지 전달 구조 개선

- NangPaGo-be/src/main/java/com/mars/NangPaGo/auth/handler/OAuth2SuccessHandler.java
- 이전 PR에서, 이미 존재하는 이메일 & 다른 Provider로 회원가입을 시도하는 경우에 대한 방어 로직이 잘못 수정된 내용을 고칩니다.
> [NO-ISSUE] 중복 이메일 회원가입 방지 로직 에러

- NangPaGo/NangPaGo-app/frontend/src/components/layout/header/Header.jsx
- NangPaGo/NangPaGo-app/frontend/src/pages/error/UnauthenticatedAccess.jsx
- NangPaGo/NangPaGo-app/frontend/src/routes/AuthenticatedRoute.jsx
- NangPaGo/NangPaGo-app/frontend/src/routes/Router.jsx
- NangPaGo/NangPaGo-app/frontend/src/slices/loginSlice.js
- 로그인 `버튼`에서 `아이콘`으로 변경
| **변경 전** | **변경 후**        |
|-----------------|---------------------------|
| <img width="96" alt="image" src="https://github.com/user-attachments/assets/f5cc5aff-2cd0-4e65-81cf-9de24b6d3fad" /> | <img width="56" alt="image" src="https://github.com/user-attachments/assets/8c07d750-7ca2-4c59-81ab-949d3b121154" /> | 
- 비로그인 사용자에 대한 헤더에 '커뮤니티' 아이콘을 추가
| **비로그인 사용자** | **로그인 사용자**        |
|-----------------|---------------------------|
| <img width="138" alt="image" src="https://github.com/user-attachments/assets/284265e2-2d21-48b4-8534-eac87f1673c8" /> | <img width="192" alt="image" src="https://github.com/user-attachments/assets/49d23209-78f0-4cac-9455-2976df9a8ae7" />  |
- **비로그인 사용자**가 `접근 제한된 페이지`에 이동하려는 경우, 자동으로 '/unauthenticated' 페이지로 리디렉션
> 접근 제한 페이지 대상: …
> [NPG-160] 리액트 라우팅에서 비로그인 사용자 접근 제한

- NangPaGo/NangPaGo-app/frontend/src/api/recipe.js
- NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
- NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/dto/RecipeFavoriteListResponseDto.java
- NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
- NangPaGo/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
- NangPaGo/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
-  페이지 번호 처리로 수정 및 조회
-  즐겨찾기한 레시피의 좋아요수와 댓글수 표시
> [NPG-162] 즐겨찾기 페이지 처리 및 좋아요/댓글수 표시

- NangPaGo-client/src/components/util/stringUtil.jsx
식재료를 검색할 때 `Object`로 반환이 되는데
> 예시 : {ingredientId: 407, highlightedName: '바<em>나</em><em>나</em>', matchScore: 20.452925}
이걸 그대로 식재료 이름으로 추가하려했기 때문에 생긴 오류였습니다.
그래서 해당 데이터의 `highlightedName`을 가져오고, `<em>`태그를 제거하도록 하였습니다.
> [NPG-195] 식재료 추가가 안되는 버그 수정

- NangPaGo-admin/src/components/DashboardLayout.jsx
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
- 관리자 페이지의 Logout URI 에 `/api` prefix가 없어, 요청에 실패(404)하는 문제를 해결합니다.
> [NO-ISSUE] 관리자 페이지 - Logout URI 수정

- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/filter/JwtAuthenticationFilter.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/handler/AdminSuccessHandler.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/service/AdminLogoutSuccessHandler.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/SecurityConfig.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/auth/service/TokenService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/filter/JwtAuthenticationFilter.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/handler/OAuth2SuccessHandler.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/auth/service/OAuth2LogoutService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/controller/AuthController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/service/TokenService.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/provider/TestJwtProvider.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/support/IntegrationTestSupport.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/util/web/CookieUtil.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/util/web/JwtUtil.java
- NangPaGo-client/src/api/axiosInstance.js
- NangPaGo-client/src/common/constants/routes.js
- NangPaGo-client/src/components/page/ErrorGuidePage.jsx
- NangPaGo-client/src/main.jsx
- NangPaGo-client/src/pages/error/LoginExpired.jsx
- NangPaGo-client/src/pages/error/NotFound.jsx
- NangPaGo-client/src/pages/error/UnauthenticatedAccess.jsx
- NangPaGo-client/src/routes/Router.jsx
- 리프레시 토큰 만료 등 reissue 요청 실패 시 클라이언트 상태를 로그아웃 상태로 처리하도록 개선합니다.
- 로그인&로그아웃 관련 쿠키 처리에 관한 중복 코드를 `common` 으로 분리합니다.
- 클라이언트 에러 페이지를 공통 컴포넌트로 분리합니다.
> [NPG-184] 토큰 재발급 실패시 로그아웃 처리

- NangPaGo-admin/src/components/DashboardLayout.jsx
- NangPaGo-client/src/components/recipe/Recipe.jsx
- 기존에 개발자가 넣어둔 레시피와 사용자가 직접 작성한 레시피를 구분하기 위해 출처를 표기함
- 관리자 화면 너비 
기존에는 화면 비율을 50% 줄였을 때, 옆으로 늘어졌음
50%로 줄였을 때도, 동일한 비율을 유지하도록 수정(=너비를 `w-[1920px]`로 고정)
> [NPG-191] 기존 레시피 출처 표기 및 관리자화면 너비 고정

- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/component/auth/AuthenticationHolder.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/controller/CommunityCommentController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/dto/CommunityCommentResponseDto.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/community/service/CommunityCommentService.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/community/service/CommunityCommentServiceTest.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/auth/UserDetailsImpl.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/util/web/JwtUtil.java
- AS-IS
- User 엔티티를 조회할 때 `findByEmail()` 로 조회.
- 인덱스가 걸려있지 않고, email string 값으로 조회하고 있으므로 조회 성능 하락 요인
- TO-BE
- `findById()` 로 조회
- 엑세스 토큰 클레임에 User.id 를 추가했으므로 구현이 가능해졌음.
- 관련 PR: https://github.com/MARS-LIKELION/NangPaGo/pull/206
- 테스트 및 예제 차원으로 CommunityComment 관련 API에 우선 적용함.
- 나머지 API도 모두 적용해야 함
> [NPG-210] 유저 조회 - `findById()`로 조회할 수 있게 개선

- NangPaGo-client/src/components/recipe/CookingStepsSlider.jsx
- 레시피 상세 페이지에서 발생한 ForwardRef 경고가 발생함
- 부모 컴포넌트에서 자식 컴포넌트의 DOM 요소에 접근하기 위해 forwardRef를 사용하도록 수정
> [NO-ISSUE] Fix: CookingStepsSlider의 ForwardRef 경고 해결

- NangPaGo-client/src/components/recipe/CookingStepsSlider.jsx
- 개선 전: md와 lg일때, 다음 요리과정을 보려면, 마우스로 드래그해서 잡아끌어야 했음.
- 개선 후: 이전 단계, 다음 단계로 넘어가는 버튼 추가 및 드래그 비활성화(`draggable: false`)
> [NPG-190] 레시피 요리과정 슬라이더 버튼 추가

- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/aop/auth/AuthenticationAspect.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/component/auth/AuthenticationHolder.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/controller/AuthController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/controller/RecipeCommentController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/dto/RecipeCommentResponseDto.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/repository/RecipeCommentRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/comment/recipe/service/RecipeCommentService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/dto/CommunityResponseDto.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/repository/UserRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/comment/recipe/service/RecipeCommentServiceTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/repository/CommunityRepositoryTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityServiceTest.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/user/User.java
- `@AuthenticatedUser`를 이용한 인증 시, 미인증 상태를 `null`로 반환하는 대신 `-1L`을 상수로 선언(`User.ANONYMOUS_USER_ID`) 하여 NPE를 방지하고 후처리 로직에서 활용할 수 있게 변경.
- RecipeComment, Community 관련 코드에 `findById` 리팩터링 적용
- 한번에 다 수정하면, 다른 PR과 충돌났을 때 해결하기 힘들 것 같아 부분 PR로 나눠서 병합시킬 예정
> [NPG-210] `findById` 리팩터링 - NPE 방지 및 일부 코드에 적용

- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/component/auth/AuthenticationHolder.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/auth/service/OAuth2ProviderTokenService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityLikeController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/repository/CommunityLikeRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/service/CommunityLikeService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/dto/RecipeLikeMessageDto.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumer.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/messaging/LikeNotificationPublisher.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/repository/RecipeLikeRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeMessageService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/service/RecipeLikeService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/refrigerator/controller/RefrigeratorController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/refrigerator/repository/RefrigeratorRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/refrigerator/service/RefrigeratorService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserService.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/community/service/CommunityLikeServiceTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/messaging/LikeNotificationConsumerTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/repository/RecipeLikeRepositoryTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeMessageServiceTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/service/RecipeLikeServiceTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/refrigerator/repository/RefrigeratorRepositoryTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/refrigerator/service/RefrigeratorServiceTest.java
- 요청 클라이언트의 User 정보 조회 쿼리에서 `email`을 조회 조건으로 사용하던 코드를 전부 `id`로 전환하는 변경을 반영합니다.
> [NPG-210] User 인증 로직에서 `findByEmail()` 제거

- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/rabbitmq/RabbitMQConfig.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/controller/RecipeFavoriteController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/dto/RecipeFavoriteMessageDto.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/dto/RecipeFavoriteResponseDto.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessageConsumer.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessagePublisher.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/repository/RecipeFavoriteRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/controller/RecipeController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/RecipeLikeMessageConsumer.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/recipe/message/RecipeLikeMessagePublisher.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessageConsumerTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/message/RecipeFavoriteMessagePublisherTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/favorite/recipe/service/RecipeFavoriteServiceTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/message/RecipeLikeMessageConsumerTest.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/recipe/message/RecipeLikeMessagePublisherTest.java
- NangPaGo-client/src/api/postStatus.js
- NangPaGo-client/src/hooks/usePostStatus.js
- 레시피 즐겨찾기 기능을 MQ 기반 비동기 처리 방식으로 개선하고, 쿼리의 Lock을 제거합니다.
> [NPG-206] 레시피 즐겨찾기 비동기로 개선

- NangPaGo-admin/src/api/usermanage.js
- NangPaGo-admin/src/pages/Users.jsx
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/controller/UserController.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/service/UserService.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/sort/SortType.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/sort/UserListSortType.java
- NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/user/service/UserServiceTest.java
- **닉네임**과 **생성일자**를 기준으로 **정렬**기능을 추가했습니다.
- `auto Increment`를 사용하여 가입기준 순서대로 들어가기 때문에 `DB` `index`설정이 되어있는 `id`로 생성일자를 정렬했습니다.
- 정렬을 하면서 닉네임 및 이메일 등의 길이 차이로 인해 위치가 고정이 안되어 있기에,
위치를 반응형에 맞게 %로 고정 및 일정 너비 이상일 시 `...`으로 표시 되도록 하였습니다.
> - **기본적으로 생성일자 내림차순으로 정렬됩니다.**
> - **사진과 같이 정렬 가능한 부분의 표시를 두었으며, 한번 더 클릭 시 오름차순 <-> 내림차순 으로 바뀝니다.**
- **생성일자**와 **닉네임**으로 정렬하는 것에 대한 **테스트 코드를 추가**했습니다.
- 테스트 코드를 작성하면서 정렬될 때, `nickname` 1부터 12까지 생성한다고 할때,
1, 11, 12, 2, 3 이런식으로 정렬 됩니다.
- 이 부분이 실제 조회했을 때 탈퇴한 유저의 닉네임이 이런식으로 정렬이 됩니다.
- `Comparator`를 사용하는 방법은 데이터를 전부 로드한 뒤 정렬해야 되어서 적용하지 않았으며,
`substr`로 해당 부분이 숫자인지를 확인하여 정렬하는 방법은
숫자가 자릿수가 계속 늘어나는 상황이나 다른 닉네임이 섞이는 등의 문제로 올바른 정렬이 되지 않았습니다.
- 우선 테스트 코드 또한 1, 11, 12, 2, 3 이런식으로 정렬 되어 확인하고 있습니다.
- 이 부분이 문제가 될 경우가 거의 탈퇴한 회원{숫자} 일텐데 `id`를 기준으로 조회하면 정상적으로 조회가 되니,
이 부분을 …
> [NPG-202] 관리자 유저 페이지 정렬 기능 추가

- NangPaGo-client/src/components/button/SocialLoginButton.jsx
- NangPaGo-client/src/globals.css
- NangPaGo-client/tailwind.config.js
- 브라우저에서 지원하는 기본 폰트로 변경
- 현재 사용 중인 Moneygraphy는 다양한 브라우저에 대응하기 어렵기 때문에 @font-face 삭제함
- 기본 폰트로 변경하면, 로그인페이지 - 소셜로그인버튼이 이렇게 보임..
- text와 label 영역의 너비를 60%(w-3/5) -> 80%(w-4/5)로 수정
> [NPG-217] 브라우저에서 지원하는 기본 폰트로 변경

- NangPaGo-client/src/components/button/RecipeButton.jsx
- NangPaGo-client/src/components/community/Community.jsx
- 수정 전: 좋아요와 즐겨찾기 아이콘이 OFF일 경우, 회색으로 채워져 있음
- 수정 후: OFF일 때, 테두리만 남기고 속이 비어있는 아이콘으로 변경(FaRegHeart, FaRegStar 추가)
> [NPG-225] 좋아요 및 즐겨찾기 아이콘 UI 변경

- NangPaGo-admin/src/api/total.js
- NangPaGo-admin/src/pages/Home.jsx
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/community/repository/CommunityRepository.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
- NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/dashboard/service/ChartServiceTest.java
- 어드민 페이지 대시보드 조회 시 월별 작성 게시글 통계를 추가했습니다.
- 조회한 날짜 기준으로 1년 이내의 데이터를 조회하여 가져옵니다.
- 조회한 데이터가 연속으로 0일 경우 안 보이도록 하였습니다. 
ex)  1월부터~7월은 데이터가 0이고, 이후 날짜부터 데이터가 있을 경우 8월부터 데이터를 보여주게 됩니다.
- 테스트 코드는 작성일자를 건드려야 하지만,
테스트를 위해 프로덕션 코드를 수정하는 것이 바람직하지않다고 생각해서 우선은 추가하지 않고,
직접 게시글을 작성해서 조회가 되는지 여부와 DB에서 날짜를 바꿔 조회되는지 확인했습니다.
>
> [NPG-226] 어드민 페이지 월별 작성 게시글 카운트 조회 기능 추가

- NangPaGo-admin/src/api/total.js
- NangPaGo-admin/src/pages/Home.jsx
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/MonthCommunityCountDto.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/MonthPostCountDto.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/MonthRegisterCountDto.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/user/repository/UserRepository.java
- NangPaGo-api/NangPaGo-admin/src/test/java/com/mars/admin/domain/dashboard/service/ChartServiceTest.java
- feat : Admin - 월별 회원가입 카운트 조회 기능 추가
- 월별 회원가입한 사용자의 "숫자"만 나타남
- Admin - dashboard 월별 통계 Dto 분리 및 "월"이 보이도록 수정
- 숫자 뒤에 "월"까지 같이 보이도록 수정
- 데이터가 없는 월(값이 0인 경우)도 그래프에 포함하여 표시
(연속적으로 데이터가 없는 월까지 포함하여 12개월을 모두 보여주고 있음..)
- Admin - 월별 회원가입 통계 그래프 디자인 개선
- 테스트 코드에서 메서드명 수정(getMonthPostCountTotals -> getPostMonthCountTotals)
- "월별 게시글 통계" 형식에 맞춰 데이터 표시하는 기능 수정
- 막대바 색상 변경 및 라인차트 추가
- 추가 제안 및 의견 : 추후에 개선시킬 경우, 월별 **회원가입** 통계에서 총사용자수만 보여주는 막대바를 가입경로(구글/카카오/네이버) 3개의 색깔로 구분하여 **누적막대** 그래프로 보여주는건 어떨까요?
라인차트의 경우에는 가입 경로 3개의 변화를 그려주면 좋을 것 같다는 생각이 듭니다..!
> [NPG-224] Admin - 월별 회원가입 카운트 조회 기능 추가 및 통계 관련 API 통합

- NangPaGo-client/src/hooks/useRefrigerator.js
Api 중복 호출로 데이터가 덮어 씌워지던 버그였으며,
주소 값이 바뀔 때 `useEffect`가 실행되던 부분을 삭제하여 수정했습니다.
해당 부분을 지우기전과 후의 로직을 설명으로 첨부합니다.
보여주는 코드 또한 이전에 있던 기존 코드입니다.
**기존 로직**
1. 재료를 선택 후 레시피를 조회한다.
2. 레시피 조회 이후 주소 값이 바뀌었기에 `1번코드` 실행 (`isMounted`가 `true`로 변경)
3. 이후 `2번 코드` 실행으로 재료 값이 변경되어 `1번코드` 실행 (`isMounted`가 `true`이기 때문에 `reFetchRefrigeratorRecipes()`실행)
4. 재료값이 초기화 된 상태에서 `reFetchRefrigeratorRecipes()`가 다시 실행되면서 모든 재료 기준으로 조회
**수정된 로직**
1. 재료를 선택 후 레시피를 조회한다.
2. 레시피 조회 이후  `2번 코드` 실행으로 재료 값이 변경되어 `1번코드` 실행 (isMounted가 true로 변경) (화면 내 변화X)
해당 코드에는 `주소가 변경`되었을 때와 `재료 값이 수정`되었을 때,
`isMounted`를 확인 후`reFetchRefrigeratorRecipes()`를 호출하여 레시피를 다시 조회하도록 되어있습니다.
```
useEffect(() => {
if (!isMounted.current) {
isMounted.current = true;
return;
}
if (location.pathname === '/refrigerator/recipe') { …
```
> [NPG-234] 내 냉장고(재료기반 레시피 조회)- 선택한 재료가 아닌 모든 재료로 조회되던 버그 수정

- NangPaGo-client/src/components/common/Modal.jsx
- NangPaGo-client/src/components/community/FileUpload.jsx
- NangPaGo-client/src/components/modal/OnlyImageUploadModal.jsx
- NangPaGo-client/src/pages/community/ModifyCommunity.jsx
- 수정 전 : 커뮤니티 & 유저 레시피 작성 시 이미지가 아닌 다른 종류의 파일(예: .xls, .pdf 등등)도 업로드 가능함
- 수정 후
- 247d45f1eb5bc48ddccc9d42c495848ca6f6f52c : 이미지가 아닌 파일을 업로드하려고할 때, Block하는 기능 추가 (alert창으로 띄우기)
- 309ca136ad57355a728e14776595f5d49e2a2720 : alert 창을 모달 팝업으로 변경
> [NPG-233] 이미지가 아닌 다른 종류의 확장자 파일 업로드가 불가능하게 수정

- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/controller/CommunityLikeController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/community/message/like/CommunityLikeMessageConsumer.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/controller/UserNotificationController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/message/UserNotificationMessageConsumer.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/repository/UserNotificationRepository.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user/service/UserNotificationService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/controller/UserRecipeCommentController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/controller/UserRecipeLikeController.java
- NangPaGo-client/src/api/notification.js
- NangPaGo-client/src/components/layout/header/ProfileDropdown.jsx
- 누락되어 있던 '커뮤니티 게시글 좋아요', '유저 레시피 좋아요', '유저 레시피 댓글' 에 대한 유저 알림 추가
- 유저가 알림을 조회할 때 읽음 처리도 동시에 하도록 변경함.
> [NPG-241] 유저 알림 발행 포인트 추가

- NangPaGo-api/NangPaGo-app/build.gradle
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/config/security/SecurityConfig.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/controller/FirebaseStorageController.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseOptimizeService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/FirebaseStorageService.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/firebase/service/ImageOptimizationService.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/exception/NPGExceptionType.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/recipe/ManualImage.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/recipe/Recipe.java
- NangPaGo-api/NangPaGo-common/src/main/java/com/mars/common/model/userRecipe/UserRecipe.java
- thumbnailator 의존성 추가 
- 이미지(사진) 리사이즈 기능 제공 해주는 라이브러리
- 이미지 사이즈 960 x 630 로 리사이징 -> 기준보다 작을 시에는 기존 크기 유지
- 압축 80%
- 결과
- 앞으로 진행 할 것 (오늘 중으로 끝날 예정)
- 현재 코드 흐름
1. 기존 레시피 이미지를 조회
2. 원본 이미지를 스토리지에 저장
3. 이미지 최적화
4. DB에 최적화된 이미지 정보 저장
- 변경하고자 하는 방향
1. 유저가 작성(등록)하거나 수정할 때 이미지를 자동으로 최적화
2. 최적화된 이미지를 스토리지에 저장
3. 동시에 DB에도 이미지 정보 저장
- CDN 적용
- 논의 해볼만 한 것 (어디서 할 지: 백엔드 vs 프론트)
- 이미지가 960×630보다 작은 경우, 원본 비율(비례)를 유지하면서 부족한 영역에 흰색 배경을 채워 
최종적으로 960×630 사이즈로 맞추고자 합니다. 
예시: 원본이 500×400이라면 기존 크기를 유지하고 나머지 공간을 흰색으로 채운 결과물이 960×630이 되도록해서 스토리지에 저장
> [NPG-213] 기존 레시피 이미지 압축 및 리사이징 

- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
- 파일이 비어 있는지 체크한 후, 실제 파일이 업로드된 경우에만 해당 파일의 URL을 반환하고 그렇지 않으면 기본 이미지 URL을 반환하도록 수정
> [NO-ISSUE] BUGFIX - 유저레시피 작성 시, firefox 업로드 과정 500에러 발생

- NangPaGo-client/src/common/styles/Image.js
- NangPaGo-client/src/components/community/Community.jsx
- NangPaGo-client/src/components/layout/Footer.jsx
- NangPaGo-client/src/components/modal/BuildVersionModal.jsx
- NangPaGo-client/src/components/recipe/Recipe.jsx
- NangPaGo-client/src/components/recipe/RecipeImage.jsx
- NangPaGo-client/src/components/search/SearchBar.jsx
- NangPaGo-client/src/components/userRecipe/UserRecipe.jsx
- 레시피 검색바 - searchTerm 폰트 색상 및 굵기 변경
- 레시피상세 - 메인이미지
- 수정 전: 각기 다른 이미지의 비율과 크기로 인해 mainImage의 크기가 각 레시피마다 조금씩 달랐음
- 수정 후: `css: object-fit의 cover` 속성을 사용해 크기가 다르더라도 일정한 크기로 보여주도록 수정
| sm | md | lg |
|:---------------------:|:---------------------:|:---------------------:|
| <img width="70%" alt="image" src="https://github.com/user-attachments/assets/5aa55c73-e272-45a2-b617-587e121e5a60" /> | <img width="500%" alt="image" src="https://github.com/user-attachments/assets/66084afc-3334-4da1-9f53-512a8d9ec8a7" /> | <img width="70%" alt="image" src="https://github.com/user-attachments/assets/6d649211-4fcf-471a-91f9-673f0aca4de6" /> |
- 커뮤니티의 메인이미지
- 기존 : 화면 너비를 기준으로 보여주고 있어서 세로 길이가 더 큰 사진이 경우 스크롤을 해서 봐야할 정도로 이미지 영역이 매우 컸음
- 수정후 : 고정된 영역을 잡아놓고(bg-gray-50), 그 영역 안에서 contain 속성으로 가로세로 비율을 유지한 채로 …
> [NO-ISSUE] 레시피 검색어 폰트 색상 변경 및 mainImage 사이즈 조정

- NangPaGo-client/src/components/recipe/Recipe.jsx
**Bug 내용**:
- `Recipe` Detail 페이지가 두 번 렌더링됨.
- `PostStatus` 버튼이 모바일/PC 뷰에서 각각 렌더링되었으나, `hidden` 처리만 되어 있어 실제로는 두 번 렌더링되고 있었음.
**변경 사항**:
1. `useCallback`으로 변경하여, `Recipe` Detail 페이지를 한 번만 렌더링.
2. `PostStatus` 버튼을 **단일 버튼**으로 통합하여 중복 렌더링 방지 및 모바일/데스크톱 뷰에 맞게 배치.
3. 모바일 뷰에서 `PostStatus` 버튼을 레시피 제목과 태그 아래로 위치 조정하여 UI 개선.
| **변경 전 모바일 UI** | **변경 후 모바일 UI** |
|------------------|------------------|
| ![변경 전 이미지](https://github.com/user-attachments/assets/1083241f-d4c5-4219-95ec-5a2c405f7e9c)  | ![변경 후 이미지](https://github.com/user-attachments/assets/43ddb196-01cf-490d-9514-d05fd257d51a)  |
> [NPG-244] BUGFIX - 레시피 디테일 페이지 내 postStatus 중복 요청

- NangPaGo-client/src/components/layout/header/Header.jsx
- NangPaGo-client/src/components/layout/header/NavItem.jsx
- NangPaGo-client/src/components/layout/header/ProfileDropdown.jsx
- NangPaGo-client/src/pages/refrigerator/Refrigerator.jsx
- 개선 전
- 현재 위치가 “레시피 추천” 페이지일 때, 노란불 들어와있는 메뉴가 아무것도 없는 상태
- 개선 후
- “추천 레시피” 라는 이름의 아이콘을 하나 더 추가해서, 메인 레시피 페이지 및 레시피 상세 페이지일 때 노란불이 들어오도록 수정
- “프로필”은 이름을 “MY” 로 바꾸기
- “냉장고”는 프로필의 마이페이지 아래로 이동
- 냉장고를 클릭시 MY의 활성화 상태가 유지되도록 함
- 냉장고 재료를 선택하고 찾기 버튼을 누르면 이동하는 추천 레시피 페이지의 header 부분을 커뮤니티와 유저레시피와 통일감을 주기 위해 `className={PAGE_STYLES.header}`를 적용
> [NPG-251] 개선: 상단 Tab 메뉴 개선 및 내냉장고 리스트  header 변경

- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/NangPaGoApplication.java
- NangPaGo-api/NangPaGo-app/src/main/java/com/mars/app/domain/user_recipe/service/UserRecipeService.java
- NangPaGo-api/NangPaGo-app/src/test/java/com/mars/app/domain/user_recipe/service/UserRecipeServiceTest.java
- NangPaGo-client/src/components/profile/ProfileTabs.jsx
- 기존에는 레시피 이미지 수정 및 삭제시 스토리지에서 이미지가 삭제가 안 되었음
- 그 결과 불필요한 이미지들이 스토리지에 저장되어 용량차지 함
- 스토리지에서 삭제 되도록 변경 
- 메서드 순서 변경
> [NPG-213] 레시피 이미지 수정 및 삭제시 스토리지에서 이미지 삭제 기능 추가

- NangPaGo-client/src/components/search/SearchBar.jsx
- NangPaGo-client/src/pages/common/ListPage.jsx
- 레시피 검색 이후 X버튼 클릭 할 때, 일부 검색 조건에 따라 X버튼 기능이 안되던 버그를 수정했습니다.
- 레시피를 검색 이후 나온 결과값이 1페이지 분량 일 경우 `URI`가 동일하여 `navigate`를 호출해도 리렌더링을 하지 않았음.
- `navigate`를 사용하던 부분을 제거하고,  레시피를 보여주는 페이지 부분에 `key`를 설정하여 변경이 되면 강제 리렌더링 
하도록 하였습니다.
> [NPG-254] 레시피 검색 이후 일부 검색 조건에 따라 X버튼 기능이 안되던 버그 수정

- NangPaGo-admin/package-lock.json
- NangPaGo-admin/package.json
- NangPaGo-admin/src/pages/Dashboard.jsx
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/controller/DashboardController.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DailyUserStatsDto.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/dto/DashboardResponseDto.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/stats/repository/VisitLogRepository.java
- 로그인/비로그인 사용자 구분하여 시각화
- 로그인: userId, 비로그인: ip 기준으로 카운트
> [NPG-256] 어드민 페이지 일일 접속자 수 통계 구현

- NangPaGo-admin/src/pages/Audit.jsx
- NangPaGo-admin/src/pages/Users.jsx
- Audit 페이지에서 row가 열려있는 상태에서 이메일(링크형식)을 클릭시
- User 페이지로 이동 -> 해당 User가 이메일로 검색된 상태로 나타남
- input 박스에 해당 이메일이 입력되어 검색 버튼이 눌린 상태(해당 사용자만 보임)
> [NPG-261] Admin - 감사 로그에서 이메일 클릭 시 User 페이지로 바로 전환

- NangPaGo-admin/src/pages/Audit.jsx
- 수정 전: 감사 로그 클릭 후 다른 페이지 넘어가면, 열어놨던 행이 다른 페이지에서도 동일하게 열려있음
- 수정 한 부분: fetchData 함수 내부에서 `setExpandedRow(null);` 를 통해 상태를 초기화
- 수정 후: 감사 로그 클릭해서 행이 열려있어도 다른 페이지로 이동하면 행이 다시 닫혀있음
> [NPG-260] 감사로그 클릭 후 다른 페이지로 이동 시 열어놨던 행이 닫히게 수정

- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/domain/dashboard/service/ChartService.java
- `USER_RECIPE`가 먼저 처리되도록 **`if-else` 문과 조건문 순서를 변경**하여 유저 레시피가 정상적으로 카운트됨
> [NPG-257] 버그: 사용자 활동 분석 차트 유저 레시피 카운트 안됨

- NangPaGo-admin/src/api/axiosInstance.js
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/auth/handler/AdminSuccessHandler.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/security/CsrfConfig.java
- NangPaGo-api/NangPaGo-admin/src/main/java/com/mars/admin/config/security/SecurityConfig.java
- Admin 페이지는 `세션 인증`방식을 사용중이므로, CSRF 공격에 대한 취약점 발생. 
- Spring Security의 CSRF 방어 기능을 활성화 하여, GET 요청을 제외한 나머지 모든 요청은 헤더에 CSRF 토큰을 포함시키지 않으면 403을 반환하도록 보안 인증 레이어를 한 단계 추가한다.
> [NPG-276] Admin - CSRF 방어 기능 활성화
